- rpm/find-provides, rpm/kernel-binary.spec.in: figure out what   subpackage is being processed in find-provides and just print   the symsets computed in the spec.

diff --git a/rpm/find-provides b/rpm/find-provides
--- a/rpm/find-provides
+++ b/rpm/find-provides
@@ -1,34 +1,40 @@
-#! /bin/sh
+#! /bin/bash
 
-IFS=$'\n'
-filelist=($(cat))
-
-printf "%s\n" "${filelist[@]}" | /usr/lib/rpm/find-provides "$@"
-
-# these two are updated by the spec file
+# these are updated by the spec file
 sourcedir=${0%/*}
 builddir="$sourcedir/../BUILD"
 
+filelist=$(mktemp -t ${0##*/}.XXXXXXXXXX)
+trap "rm -f $filelist" EXIT
+cat >"$filelist"
 flavor=${1##*-}
 
-modlist=$(mktemp -t ${0##*/}.XXXXXXXXXX)
-trap "rm -rf $modlist" EXIT
+/usr/lib/rpm/find-provides "$@" <"$filelist"
 
-symvers=
-for file in "${filelist[@]}"; do
-    case "$file" in 
-    */Module.symvers)
-	symvers="--symvers-file=$file"
-	;;
-    *.ko)
-	echo "$file" >>"$modlist"
-	;;
-    esac
-done
+# HACK: find out what subpackage is this and just print the symsets
+# computed in %build. We need to do it this way because the provided
+# symsets are computed from the modules AND the reference symsets, which
+# we don't see here.
+subpack=
 
-reference=
-# TODO
-# reference="--reference=$builddir/kabi/..."
-$sourcedir/symsets.pl --list-symsets --modules=$modlist $symvers $reference |\
-    sed -rn 's/^(.+)\.([a-z0-9]{16})/kernel('$flavor':\1) = \2/p'
+samemodules()
+{
+    cmp -s <(sed -rn 's:.*/([^/]*\.ko)$:\1:p' "$1" | sort) \
+           <(sed -rn 's:.*/([^/]*\.ko)$:\1:p' "$2" | sort)
+}
+
+if   samemodules "$builddir"/base-modules "$filelist"; then
+    subpack=base
+elif samemodules "$builddir"/main-modules "$filelist"; then
+    subpack=main
+elif samemodules "$builddir"/unsupported-modules "$filelist"; then
+    subpack=extra
+else
+    echo "find-provides: failed to determine which subpackage is this" >&2
+    exit 1
+fi
+
+ls "$builddir/$subpack-symsets" | sed -rn 's/^(.+)\.([a-z0-9]{16})/kernel('$flavor':\1) = \2/p'
+
+exit 0
 
