- Add a flag for ignoring failures in external modules. - For now, don't fail: one of the km_* package is screwed up again.

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -57,6 +57,9 @@ NoSource:     103
 NoSource:     104
 NoSource:     105
 
+# Will failures in external modules abort the kernel build?
+%define extmod_failures_are_fatal 0
+
 %(chmod +x %_sourcedir/{arch-symbols,guards,config-subst,check-for-config-changes})
 %define ver_str %kversion-%release-@CFGNAME@
 %define symbols %(export PATCH_ARCH=%_target_cpu ; cd %_sourcedir ; echo $(./arch-symbols) $([ -e extra-symbols ] && cat extra-symbols))
@@ -178,8 +181,14 @@ for dir in /usr/src/kernel-modules/*; do
 	build_dir=%_builddir/modules-%kversion/${dir##*/}
 	cp -r $dir $build_dir
 
-	make -C $build_dir %{?jobs:-j%jobs} modules $MAKE_ARGS \
-	    KERNEL_SOURCE=%_builddir/linux-%kversion
+	rm -f $build_dir-failed
+	if ! make -C $build_dir %{?jobs:-j%jobs} modules $MAKE_ARGS \
+		  KERNEL_SOURCE=%_builddir/linux-%kversion; then
+%if %extmod_failures_are_fatal
+	    exit 1
+%endif
+	    touch $build_dir-failed
+	fi
     fi
 done
 shopt -u nullglob
@@ -244,9 +253,13 @@ touch -d "$(cat kernel-source/build-source-timestamp)" \
 
 shopt -s nullglob
 for build_dir in %_builddir/modules-%kversion/* ; do
-    make -C $build_dir install $MAKE_ARGS \
-	KERNEL_SOURCE=%_builddir/linux-%kversion \
-	INSTALL_MOD_PATH=%buildroot
+    if [ -e $build_dir-failed ]; then
+	echo "Build of $build_dir has failed"
+    else
+	make -C $build_dir install $MAKE_ARGS \
+	    KERNEL_SOURCE=%_builddir/linux-%kversion \
+	    INSTALL_MOD_PATH=%buildroot
+    fi
 done
 shopt -u nullglob
 
