rpm/kernel-binary.spec.in: Check module licenses (bsc#1083215,bsc#1083527)

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -713,6 +713,14 @@ if [ %CONFIG_MODULES = y ]; then
 	fi
     fi
 
+    # Check the license in each module
+    if ! sh %_sourcedir/check-module-license %buildroot; then
+	echo "Please fix the missing licenses!"
+%if %CONFIG_SUSE_KERNEL_SUPPORTED == "y"
+	exit 1
+%endif
+    fi
+
     # These files are required for building external modules
     for FILE in arch/powerpc/lib/crtsavres.o arch/arm64/kernel/ftrace-mod.o; do
 	    if [ -f %kernel_build_dir/$FILE ]; then
