- Copy config files into the tree after patching: doing it before that broke the build, because some patches are touching defconfig files.

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -108,6 +108,24 @@ fi
 flavor=${1#*/}
 subarch=${1%/*}
 
+# Apply the patches needed for this architecture.
+for patch in $(%_sourcedir/guards %symbols < %_sourcedir/series.conf); do
+    if ! patch -s -E -p1 --no-backup-if-mismatch -i ../$patch; then
+	echo "*** Patch $patch failed ***"
+	exit 1
+    fi
+done
+
+# We allow to apply an additional patch for custom builds
+if [ -e %_sourcedir/$subarch-$flavor.diff ]; then
+    echo "Applying additional patch $subarch-$flavor.diff"
+    if ! patch -s -E -p1 --no-backup-if-mismatch \
+	       -i %_sourcedir/$subarch-$flavor.diff; then
+	echo "*** Patch $patch failed ***"
+	exit 1
+    fi
+fi
+
 # We allow to override the config file for custom builds
 if [ -e %_sourcedir/$subarch-$flavor.conf ]; then
     echo "Using override config file $subarch-$flavor.conf"
@@ -140,24 +158,6 @@ MAKE_ARGS="ARCH=$subarch"
 CONFIG=$config
 EOF
 %endif
-
-# Apply the patches needed for this architecture.
-for patch in $(%_sourcedir/guards %symbols < %_sourcedir/series.conf); do
-    if ! patch -s -E -p1 --no-backup-if-mismatch -i ../$patch; then
-	echo "*** Patch $patch failed ***"
-	exit 1
-    fi
-done
-
-# We allow to apply an additional patch for custom builds
-if [ -e %_sourcedir/$subarch-$flavor.diff ]; then
-    echo "Applying additional patch $subarch-$flavor.diff"
-    if ! patch -s -E -p1 --no-backup-if-mismatch \
-	       -i %_sourcedir/$subarch-$flavor.diff; then
-	echo "*** Patch $patch failed ***"
-	exit 1
-    fi
-fi
 
 # Create the scipts for %pre, %post, %preun, %postun
 for when in pre preun post postun ; do
