- rpm/kernel-source.spec.in: Prepare for the upcoming introduction   of kernel-source-rt (and kernel-syms-rt) for producing KMPs for   real-time kernels. - rpm/install-configs: Remove; this script didn't improve things.

diff --git a/rpm/kernel-source.spec.in b/rpm/kernel-source.spec.in
--- a/rpm/kernel-source.spec.in
+++ b/rpm/kernel-source.spec.in
@@ -11,6 +11,8 @@
 # norootforbuild
 # icecream 0
 
+# FIXME: this check will go before the next release ...
+
 %if 0%{?opensuse_bs}
 # Strip off the build number ("y") from the "x.y" release number
 %define source_rel %(release=%release; echo ${release%.*})
@@ -27,6 +29,7 @@ License:      GPL
 Group:        Development/Sources
 AutoReqProv:  off
 BuildRequires:  coreutils sed
+BuildRequires:  fdupes
 Requires(post): coreutils sed
 %if ! 0%{?opensuse_bs}
 BuildRequires:  kernel-dummy
@@ -54,7 +57,6 @@ Source23:     supported.conf
 Source30:     config-subst
 Source33:     check-for-config-changes
 Source34:     check-supported-list
-Source35:     install-configs
 Source37:     README.SUSE
 Source38:     kabi-checks
 Source40:     build-source-timestamp
@@ -84,11 +86,16 @@ Source120:    kabi.tar.bz2
 BuildRoot:    %_tmppath/%name-%version-build
 Prefix:       /usr/src
 
-%(chmod +x %_sourcedir/{arch-symbols,guards,config-subst,check-for-config-changes,kabi-checks,install-configs})
+# Build with bash instead of sh as the shell: this turns on bash
+# extensions like <(...).
+%define _buildshell /bin/bash
+
+%(chmod +x %_sourcedir/{arch-symbols,guards,config-subst,check-for-config-changes,kabi-checks})
 
 %define symbols %(set -- $(%_sourcedir/arch-symbols %_target_cpu) $([ -e %_sourcedir/extra-symbols ] && cat %_sourcedir/extra-symbols) ; echo $*)
 
 %define tolerate_unknown_new_config_options @TOLERATE_UNKNOWN_NEW_CONFIG_OPTIONS@
+%define with_rt 0
 
 %description
 Dummy description.
@@ -105,35 +112,11 @@ echo "Architecture symbol(s): %symbols"
 %setup -q -c -T -a 100 -a 101 -a 102 -a 103 -a 104 -a 105 -a 106 -a 107 -a 108 -a 109 -a 110 -a 111 -a 112
 
 %build
-mkdir -p $RPM_BUILD_ROOT/usr/src
-cd $RPM_BUILD_ROOT/usr/src
-
-# Unpack the vanilla kernel sources
-bzip2 -cd %_sourcedir/linux-@SRCVERSION@.tar.bz2 \
-| tar xf -
-cd linux-@SRCVERSION@
-
-# Apply the patches needed for this architecture.
-%_sourcedir/guards %symbols < %_sourcedir/series.conf \
-    > %_builddir/@NAME@-@RPMVERSION@/kernel-source.patches
-for patch in $(< %_builddir/@NAME@-@RPMVERSION@/kernel-source.patches); do
-    if ! patch -s -F0 -E -p1 --no-backup-if-mismatch -i %_builddir/@NAME@-@RPMVERSION@/$patch; then
-	echo "*** Patch $patch failed ***"
-	exit 1
-    fi
-done
-
 # Release number without the EXTRAVERSION
 RELEASE=%source_rel
 while [ "$RELEASE" != "${RELEASE#[^0-9]*.}" ]; do
     RELEASE=${RELEASE#[^0-9]*.}
 done
-
-if [ -f %_sourcedir/localversion ] ; then
-    cat %_sourcedir/localversion > localversion
-fi
-
-%_sourcedir/install-configs %_sourcedir %_builddir/%buildsubdir $RELEASE
 
 KERNELRELEASE=@PATCHVERSION@-$RELEASE
 cat > %_builddir/%{name}-%{version}/.rpm-defs <<EOF
@@ -141,15 +124,45 @@ KERNELRELEASE=$KERNELRELEASE
 SYMBOLS="%symbols"
 EOF
 
-cd ..
-mv linux-@SRCVERSION@ linux-$KERNELRELEASE
-cd linux-$KERNELRELEASE
+create_source_tree() {
+    local name=$1 extrasymbols
+    shift ; extrasymbols=$*
 
-cd $RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE
+    cp -rld linux-@SRCVERSION@.orig $name
+    cd $name
+    %_sourcedir/guards %symbols $extrasymbols < %_sourcedir/series.conf \
+	> .patches
+    for patch in $(< .patches); do
+	if ! patch -s -F0 -E -p1 --no-backup-if-mismatch \
+		  -i %_builddir/@NAME@-@RPMVERSION@/$patch; then
+	echo "*** Patch $patch failed ***"
+	exit 1
+	fi
+    done
+
+    if [ -f %_sourcedir/localversion ] ; then
+	cat %_sourcedir/localversion > localversion
+    fi
+    cd ..
+}
+
+mkdir -p $RPM_BUILD_ROOT/usr/src
+cd $RPM_BUILD_ROOT/usr/src
+
+# Unpack the vanilla kernel sources
+bzip2 -cd %_sourcedir/linux-@SRCVERSION@.tar.bz2 \
+| tar xf -
+mv linux-@SRCVERSION@ linux-@SRCVERSION@.orig
+
+create_source_tree linux-$KERNELRELEASE
+%if %with_rt
+create_source_tree linux-$KERNELRELEASE-rt RT
+%endif
+
 for config in $(%_sourcedir/guards %symbols < %_sourcedir/config.conf | grep -v vanilla); do
     arch=${config%/*}
     flavor=${config#*/}
-    config=arch/$arch/defconfig.$flavor
+    config=%_builddir/%buildsubdir/config/$config
 
     case "$flavor" in
     *-*)
@@ -158,15 +171,28 @@ for config in $(%_sourcedir/guards %symbols < %_sourcedir/config.conf | grep -v 
 	;;
     esac
 
-    set -- kernel-$flavor $flavor $(case $flavor in (rt|rt_*) echo RT ;; esac)
-    %_sourcedir/guards $* %symbols < %_sourcedir/series.conf \
-	> %_builddir/@NAME@-@RPMVERSION@/kernel-$flavor.patches
-    diff -q %_builddir/@NAME@-@RPMVERSION@/kernel-{source,$flavor}.patches \
+    set -- kernel-$flavor $flavor
+    case $flavor in
+    (rt|rt_*)
+	set -- "$@" RT
+	source_tree=linux-$KERNELRELEASE-rt
+	;;
+    (*)
+	source_tree=linux-$KERNELRELEASE
+	;;
+    esac
+
+    diff -q $source_tree/.patches \
+	    <(%_sourcedir/guards $* %symbols < %_sourcedir/series.conf) \
 	|| continue
 
     o=$RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE-obj/$arch/$flavor
     mkdir -p $o
-    cp $config $o/.config
+    cat $config \
+    | %_sourcedir/config-subst CONFIG_LOCALVERSION '"'-$flavor'"' \
+    | %_sourcedir/config-subst CONFIG_SUSE_KERNEL y \
+    > $o/.config
+    echo "-$RELEASE" > $source_tree/localversion-rpm-release
 
     case $flavor in
     um)
@@ -182,58 +208,39 @@ for config in $(%_sourcedir/guards %symbols < %_sourcedir/config.conf | grep -v 
 %if %{tolerate_unknown_new_config_options}
     yes '' | make oldconfig $MAKE_ARGS
 %else
-    make silentoldconfig $MAKE_ARGS < /dev/null
+    make -C $source_tree silentoldconfig $MAKE_ARGS < /dev/null
     %_sourcedir/check-for-config-changes $config $o/.config
 %endif
 
-    make prepare $MAKE_ARGS
-    make scripts $MAKE_ARGS
-
-    krel=$(make -s kernelrelease $MAKE_ARGS)
+    make -C $source_tree prepare $MAKE_ARGS
+    make -C $source_tree scripts $MAKE_ARGS
+    krel=$(make -C $source_tree -s kernelrelease $MAKE_ARGS)
     if [ $KERNELRELEASE != "${krel%%-*}" ]; then
 	echo "Kernel release mismatch: $KERNELRELEASE != ${krel%%-*}" >&2
 	exit 1
     fi
+    make -C $source_tree clean $MAKE_ARGS
 
-    mkdir -p ../../../lib/modules/$krel/
+    mkdir -p $RPM_BUILD_ROOT/lib/modules/$krel
     ln -s ../../../usr/src/linux-$KERNELRELEASE \
-    	../../../lib/modules/$krel/source
-
-    make clean $MAKE_ARGS
-    rm -f $o/.config.old
+    	$RPM_BUILD_ROOT/lib/modules/$krel/source
 
     # Replace the absolute with a relative path
     sed -e "s,$RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE,../../../linux-$KERNELRELEASE,g" \
 	-i $o/Makefile
+    rm -f $o/.config.old
 done
+
+rm -rf linux-@SRCVERSION@.orig
+rm -f linux-$KERNELRELEASE/.patches
+%if %with_rt
+rm -f linux-$KERNELRELEASE-rt/.patches
+%endif
+
+# Hardlink duplicate files automatically (from package fdupes).
+%fdupes $RPM_BUILD_ROOT
 
 cd $RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE-obj
-set -- */*
-for arch_flavor in $* ; do
-    if ! [ -e obj.files ]; then
-	(cd $arch_flavor ; find -type f) > obj.files
-    fi
-
-    # Strip ELF files
-    while read file ; do
-	strip $file
-    done <<-EOF
-	$(xargs -i% file $arch_flavor/% < obj.files \
-	    | grep ELF \
-	    | sed -e 's/: .*//')
-	EOF
-
-    if [ $arch_flavor != $1 ]; then
-	while read file ; do
-	    if [ -s $arch_flavor/$file ] \
-	       && cmp -s $1/$file $arch_flavor/$file ; then
-		ln -f $1/$file $arch_flavor/$file
-	    fi
-	done < obj.files
-    fi
-done
-rm -f obj.files
-
 set -- *
 [ -e %_target_cpu ] || ln -s $1 %_target_cpu
 %ifarch ppc ppc64
@@ -283,10 +290,37 @@ cat > kernel-source.files <<EOF
 /lib/modules/*
 EOF
 
-(   cat %_sourcedir/functions.sh
-    sed -e "s:@KERNELRELEASE@:$KERNELRELEASE:g" %_sourcedir/source-post.sh
-) > source-post.sh
+%if %with_rt
+cat > kernel-source-rt.files <<EOF
+%%defattr(-, root, root)
+FIXME: splitting cleanly needs some work here.
+EOF
+%endif
+
+for variant in '' '-rt'; do
+    (   cat %_sourcedir/functions.sh
+	sed -e "s:@KERNELRELEASE@:$KERNELRELEASE:g" \
+	    -e "s:@VARIANT@:$variant:g" \
+	    %_sourcedir/source-post.sh
+    ) > source-post$variant.sh
+done
 
 %post -f source-post.sh
 
 %files -f kernel-source.files
+
+%package -n @NAME@-rt
+Summary:      Dummy summary
+License:      GPL
+Group:        Development/Sources
+Requires(post): coreutils sed
+Provides:       kernel-source-rt = @RPMVERSION@-%source_rel
+
+%description -n @NAME@-rt
+Dummy description.
+
+%post -n @NAME@-rt -f source-post-rt.sh
+
+%if %with_rt
+%files -n @NAME@-rt -f kernel-source.files
+%endif
