- rpm/kernel-binary.spec.in, rpm/kernel-source.spec.in: simplify   the patch applying loops to reduce noise in build logs.

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -255,22 +255,15 @@ comm -2 -3 <(supported_conf base) <(supported_conf) \
 
 cd linux-%srcversion
 
-# Apply the patches needed for this architecture.
-%if ! %build_vanilla
-for patch in $(%_sourcedir/guards %symbols < %_sourcedir/series.conf); do
-    if ! patch -s -F0 -E -p1 --no-backup-if-mismatch -i ../$patch; then
-	echo "*** Patch $patch failed ***"
-	exit 1
-    fi
-done
-%else
-for patch in $(%_sourcedir/guards %symbols < %_sourcedir/series.conf | egrep 'kernel\.org|rpmify'); do
-    if ! patch -s -F0 -E -p1 --no-backup-if-mismatch -i ../$patch; then
-	echo "*** Patch $patch failed ***"
-	exit 1
-    fi
-done
+# Apply patches
+echo "trap 'echo \"*** patch \$_ failed ***\"' ERR" >../apply-patches.sh
+%_sourcedir/guards %symbols <%_sourcedir/series.conf | \
+%if %build_vanilla
+    egrep '^patches\.(kernel\.org|rpmify)/' | \
 %endif
+    sed 's:^:patch -s -F0 -E -p1 --no-backup-if-mismatch -i ../:' \
+    >>../apply-patches.sh
+bash -ex ../apply-patches.sh
 
 cd %kernel_build_dir
 
