- No loger abort the build when modules are not listed in   supported.conf.

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -62,6 +62,9 @@ NoSource:     105
 # Will failures in external modules abort the kernel build?
 %define extmod_failures_are_fatal 1
 
+# Will modules not listed in supported.conf abort the kernel build?
+%define supported_modules_check 0
+
 %(chmod +x %_sourcedir/{arch-symbols,guards,config-subst,check-for-config-changes,check-supported-list})
 %define ver_str %kversion-%release-@CFGNAME@
 %define symbols %(export PATCH_ARCH=%_target_cpu ; cd %_sourcedir ; echo $(./arch-symbols) $([ -e extra-symbols ] && cat extra-symbols))
@@ -198,6 +201,7 @@ for dir in /usr/src/kernel-modules/*; do
 %if %extmod_failures_are_fatal
 	    exit 1
 %endif
+	    echo "External module error: $dir failed"
 	    touch $build_dir-failed
 	fi
     fi
@@ -280,8 +284,13 @@ for build_dir in %my_builddir/modules-%kversion/* ; do
 done
 shopt -u nullglob
 
-%_sourcedir/check-supported-list \
-    %_sourcedir %buildroot/lib/modules/%ver_str
+if ! %_sourcedir/check-supported-list \
+	%_sourcedir %buildroot/lib/modules/%ver_str; then
+%if %supported_modules_check
+    exit 1
+%endif
+    echo "Consistency check error: please update supported.conf."
+fi
 
 # We were building in %my_builddir/linux-%kversion, but the sources will
 # later be installed in /usr/src/linux-%kversion-%release. Fix up the
