- improve error logging in case the kernel module could not get loaded

diff --git a/rpm/kernel-obs-qa.spec.in b/rpm/kernel-obs-qa.spec.in
--- a/rpm/kernel-obs-qa.spec.in
+++ b/rpm/kernel-obs-qa.spec.in
@@ -56,7 +56,15 @@ projects and runs basic tests.
 # test suites should be packaged in other packages, but build required
 # and called here.
 
-/sbin/modprobe loop || exit 1
+if ! /sbin/modprobe loop; then
+  echo "ERROR: Unable to load the kernel loop module."
+  echo "Usually the wrong kernel is running, this is atm"
+  cat /proc/version
+  echo "Installed kernel modules are:"
+  rpm -q kernel-@FLAVOR@
+  exit 1
+fi
+
 
 %install
 mkdir -p %{buildroot}/usr/share/kernel-qa/
