- rpm/kernel-binary.spec.in: replace OSRELEASE of makedumpfile   configuration file with version of kernel that is built   instead of the running kernel -- for this, the PAGESIZE   of that file needs to be patched on IA64 (IA64 is still   un-enabled until the makedumpfile patches are all mainline   and we have a new makedumpfile package)

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -47,9 +47,7 @@ Autoreqprov:    on
 BuildRequires:  coreutils module-init-tools
 
 %if %suse_version > 1020
-%ifarch %ix86 x86_64 ppc ppc64
 BuildRequires:  makedumpfile
-%endif
 %endif
 
 Requires(post): module-init-tools
@@ -468,9 +466,32 @@ fi
 #
 # create configfile for makedumpfile utility (see makedumpfile(8)) to
 # create smaller kdump images
+CONFIGFILE=%buildroot/$obj_dir/$SUBARCH/default/makedumpfile.config
 makedumpfile -x %buildroot/usr/lib/debug/boot/vmlinux-$KERNELRELEASE.debug \
-        -g %buildroot/$obj_dir/$SUBARCH/default/makedumpfile.config \
-        || true  # failure should not fail the build
+        -g $CONFIGFILE || true  # failure should not fail the build
+
+if [ -f $CONFIGFILE ] ; then
+
+    #
+    # fixup config file with current kernel version
+    sed -i $CONFIGFILE -e "s/OSRELEASE=.*/OSRELEASE=$KERNELRELEASE/"
+
+    #
+    # on IA64, we need to add the page size here -- that's the actual reason why
+    # the makedumpfile tool relies on the running kernel and not on the compiled
+    # kernel -- it's (nearly) impossible to get the page size of a vmlinux file.
+    %ifarch ia64
+    if grep CONFIG_IA64_PAGE_SIZE_16KB $CONFIGFILE >/dev/null ; then
+        sed -i $CONFIGFILE -e "s/PAGESIZE=.*/PAGESIZE=16384/"
+    elif grep CONFIG_IA64_PAGE_SIZE_64KB $CONFIGFILE >/dev/null ; then
+        sed -i $CONFIGFILE -e "s/PAGESIZE=.*/PAGESIZE=65536/"
+    elif grep CONFIG_IA64_PAGE_SIZE_4KB  $CONFIGFILE >/dev/null ; then
+        sed -i $CONFIGFILE -e "s/PAGESIZE=.*/PAGESIZE=4096/"
+    else
+        sed -i $CONFIGFILE -e "s/PAGESIZE=.*/PAGESIZE=8192/"
+    fi
+    %endif
+fi
 
 %endif
 %endif
