- Similar to the override configuration $arch-$flavor.conf, check for   $arch-$flavor.diff: If it exists, apply this patch after all other   patches in series.conf. This is again intended for test builds.

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -78,28 +78,12 @@ echo "Architecture symbol(s): %symbols"
 # points to the right path, linux-%kversion
 %setup -q -n linux-%kversion
 
-# Apply the patches needed for this architecture.
-for patch in $(%_sourcedir/guards %symbols < %_sourcedir/series.conf); do
-    if ! patch -s -E -p1 --no-backup-if-mismatch -i ../$patch; then
-	echo "*** Patch $patch failed ***"
-	exit 1
-    fi
-done
-
-for when in pre preun post postun ; do
-    sed -e "s/@when@/$when/g" %_sourcedir/trigger-script.sh.in > $when.sh
-done
-
-cat %_sourcedir/{functions.sh,post.sh}  >> post.sh
-cat %_sourcedir/{functions.sh,postun.sh} >> postun.sh
-
 # Find out for which architecture to build. We do this here, and use the
 # result in the %build and %install sections.
 #
 # On architectures with a bi-arch or cross compiler, we can compile for
 # an architecture different from %arch. The location of the config file
 # tells us for which architecture to compile.
-
 set -- $(
     for config in $(%_sourcedir/guards %symbols < %_sourcedir/config.conf) ; do
 	[ ${config#*/} = @CFGNAME@ ] || continue
@@ -113,6 +97,7 @@ flavor=${1#*/}
 subarch=${1%/*}
 config=../config/$subarch/$flavor
 
+# We allow to override the config file for custom builds
 if [ -e %_sourcedir/$subarch-$flavor.conf ]; then
     echo "Using override config file $subarch-$flavor.conf"
     config=%_sourcedir/$subarch-$flavor.conf
@@ -132,6 +117,32 @@ MAKE_ARGS="ARCH=$subarch"
 CONFIG=$config
 EOF
 %endif
+
+# Apply the patches needed for this architecture.
+for patch in $(%_sourcedir/guards %symbols < %_sourcedir/series.conf); do
+    if ! patch -s -E -p1 --no-backup-if-mismatch -i ../$patch; then
+	echo "*** Patch $patch failed ***"
+	exit 1
+    fi
+done
+
+# We allow to apply an additional patch for custom builds
+if [ -e %_sourcedir/$subarch-$flavor.diff ]; then
+    echo "Applying additional patch $subarch-$flavor.conf"
+    if ! patch -s -E -p1 --no-backup-if-mismatch \
+	       -i %_sourcedir/$subarch-$flavor.diff; then
+	echo "*** Patch $patch failed ***"
+	exit 1
+    fi
+fi
+
+# Create the scipts for %pre, %post, $preun, %postun
+for when in pre preun post postun ; do
+    sed -e "s/@when@/$when/g" %_sourcedir/trigger-script.sh.in > $when.sh
+done
+
+cat %_sourcedir/{functions.sh,post.sh}  >> post.sh
+cat %_sourcedir/{functions.sh,postun.sh} >> postun.sh
 
 %build
 source .rpm-defs
