kernel-source: Create kernel-source-vanilla
This patch creates a kernel-source-vanilla package that contain the sources
as used to build the kernel-vanilla flavor.

diff --git a/rpm/kernel-source.spec.in b/rpm/kernel-source.spec.in
--- a/rpm/kernel-source.spec.in
+++ b/rpm/kernel-source.spec.in
@@ -102,8 +102,25 @@ Prefix:       /usr/src
 %define symbols %(set -- $([ -e %_sourcedir/extra-symbols ] && cat %_sourcedir/extra-symbols) ; echo $*)
 %define variant_symbols %(case %name in (*-rt) echo "RT" ;; esac)
 
+%define do_vanilla "%variant" == ""
+
 %description
 Dummy description.
+
+%package vanilla
+Summary: Vanilla Linux kernel sources with minor build fixes.
+Group:        Development/Sources
+AutoReqProv:  off
+
+%description vanilla
+Vanilla Linux kernel sources with minor build fixes.
+
+
+Authors:
+--------
+    Linus Torvalds <torvalds@osdl.org>
+
+    see /usr/src/linux/CREDITS for more details.
 
 %prep
 if ! [ -e %_sourcedir/linux-%srcversion.tar.bz2 ]; then
@@ -133,9 +150,23 @@ bzip2 -cd %_sourcedir/linux-%srcversion.tar.bz2 \
 | tar xf -
 
 mv linux-%srcversion linux-%kernelrelease%variant
-cd linux-%kernelrelease%variant
+%if %do_vanilla
+cp -al linux-%kernelrelease%variant linux-%kernelrelease-vanilla
+cd linux-%kernelrelease-vanilla
+%_sourcedir/guards %variant_symbols %symbols < %_sourcedir/series.conf |
+	egrep kernel.org\|rpmify > .patches
+for patch in $(< .patches); do
+    if ! patch -s -F0 -E -p1 --no-backup-if-mismatch \
+	      -i %_builddir/%name-%version/$patch; then
+    echo "*** Patch $patch failed ***"
+    exit 1
+    fi
+done
+rm -f .patches $(find . -name ".gitignore")
+cd ..
+%endif
 
-chmod -x arch/arm/mach-at91/board-yl-9200.c # executable by accident (fixed in 2.6.27)
+cd linux-%kernelrelease%variant
 
 %_sourcedir/guards %variant_symbols %symbols < %_sourcedir/series.conf \
     > .patches
@@ -147,13 +178,11 @@ for patch in $(< .patches); do
     fi
 done
 
-rm -f $(find . -name ".gitignore")
+rm -f .patches $(find . -name ".gitignore")
 
 if [ -f %_sourcedir/localversion ] ; then
     cat %_sourcedir/localversion > localversion
 fi
-
-rm -f .patches
 
 # Hardlink duplicate files automatically (from package fdupes).
 %fdupes $RPM_BUILD_ROOT
@@ -187,3 +216,9 @@ done
 /etc/rpm/macros.kernel-source
 /usr/lib/rpm/kernel-module-subpackage
 /%src_install_dir
+
+%if %do_vanilla
+%files vanilla
+%defattr(-, root, root)
+/usr/src/linux-%kernelrelease-vanilla
+%endif
