- add 'vanilla' kernel build to the system.

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -21,6 +21,7 @@
 %define build_kdump %([ @FLAVOR@ != kdump ] ; echo $?)
 %define build_xen %(case @FLAVOR@ in (xen*) echo 1;; (*) echo 0;; esac)
 %define build_um  %([ @FLAVOR@ != um ] ; echo $?)
+%define build_vanilla  %([ @FLAVOR@ != vanilla ] ; echo $?)
 
 Name:         @NAME@
 BuildRequires:  kernel-dummy @EXTRA_NEEDS@
@@ -172,12 +173,21 @@ fi
 subarch=${1%/*}
 
 # Apply the patches needed for this architecture.
+%if !%build_vanilla
 for patch in $(%_sourcedir/guards $symbols < %_sourcedir/series.conf); do
     if ! patch -s -E -p1 --no-backup-if-mismatch -i ../$patch; then
 	echo "*** Patch $patch failed ***"
 	exit 1
     fi
 done
+%else
+for patch in $(%_sourcedir/guards $symbols < %_sourcedir/series.conf | egrep kernel.org\|rpmify); do
+    if ! patch -s -E -p1 --no-backup-if-mismatch -i ../$patch; then
+	echo "*** Patch $patch failed ***"
+	exit 1
+    fi
+done
+%endif
 
 %_sourcedir/install-configs %_sourcedir %my_builddir %dummy_release
 config=arch/$subarch/defconfig.@FLAVOR@
@@ -353,7 +363,7 @@ add_vmlinux()
 # kdump
 %endif
 
-%if %build_kdump || %build_um || %build_xen
+%if %build_kdump || %build_um || %build_xen || %build_vanilla
 suffix=-@FLAVOR@
 %endif
 ln -s $image$suffix %buildroot/boot/$image$suffix
