- Introduce kernel-source-rt and kernel-syms-rt packages, needed   for building real-time KMPs.

diff --git a/rpm/kernel-source.spec.in b/rpm/kernel-source.spec.in
--- a/rpm/kernel-source.spec.in
+++ b/rpm/kernel-source.spec.in
@@ -34,6 +34,7 @@ Requires(post): coreutils sed
 %if ! 0%{?opensuse_bs}
 BuildRequires:  kernel-dummy
 %endif
+ExclusiveArch: @ARCHS@
 Provides:       linux
 Provides:       kernel-source = @RPMVERSION@-%source_rel
 %if "@NAME@" == "kernel-source"
@@ -43,9 +44,7 @@ Obsoletes:    linux lx-gdt lx-hack lx-suse lx1162_1 lx1162_2 lx1212_1 lx1212_2 l
 Source0:      http://www.kernel.org/pub/linux/kernel/v2.6/linux-@SRCVERSION@.tar.bz2
 Source1:      functions.sh
 Source2:      source-post.sh
-%if "@NAME@" == "kernel-source"
-Source3:      kernel-source.rpmlintrc
-%endif
+Source3:      @NAME@.rpmlintrc
 Source10:     pre.sh
 Source11:     post.sh
 Source12:     postun.sh
@@ -97,7 +96,6 @@ Prefix:       /usr/src
 %define symbols %(set -- $(%_sourcedir/arch-symbols %_target_cpu) $([ -e %_sourcedir/extra-symbols ] && cat %_sourcedir/extra-symbols) ; echo $*)
 
 %define tolerate_unknown_new_config_options @TOLERATE_UNKNOWN_NEW_CONFIG_OPTIONS@
-%define with_rt 0
 
 %description
 Dummy description.
@@ -113,8 +111,6 @@ echo "Architecture symbol(s): %symbols"
 # Unpack all sources and patches
 %setup -q -c -T -a 100 -a 101 -a 102 -a 103 -a 104 -a 105 -a 106 -a 107 -a 108 -a 109 -a 110 -a 111 -a 112
 
-#chmod -x arch/arm/mach-at91/board-yl-9200.c # executable by accident (fixed in 2.6.27)
-
 %build
 # Release number without the EXTRAVERSION
 RELEASE=%source_rel
@@ -123,32 +119,22 @@ while [ "$RELEASE" != "${RELEASE#[^0-9]*.}" ]; do
 done
 
 KERNELRELEASE=@PATCHVERSION@-$RELEASE
+
+case @NAME@ in
+(*-rt)
+    variant=-rt
+    variant_symbols=RT
+    ;;
+(*)
+    variant=
+    variant_symbols=
+    ;;
+esac
+
 cat > %_builddir/%{name}-%{version}/.rpm-defs <<EOF
 KERNELRELEASE=$KERNELRELEASE
-SYMBOLS="%symbols"
+variant=$variant
 EOF
-
-create_source_tree() {
-    local name=$1 extrasymbols
-    shift ; extrasymbols=$*
-
-    cp -rld linux-@SRCVERSION@.orig $name
-    cd $name
-    %_sourcedir/guards %symbols $extrasymbols < %_sourcedir/series.conf \
-	> .patches
-    for patch in $(< .patches); do
-	if ! patch -s -F0 -E -p1 --no-backup-if-mismatch \
-		  -i %_builddir/@NAME@-@RPMVERSION@/$patch; then
-	echo "*** Patch $patch failed ***"
-	exit 1
-	fi
-    done
-
-    if [ -f %_sourcedir/localversion ] ; then
-	cat %_sourcedir/localversion > localversion
-    fi
-    cd ..
-}
 
 mkdir -p $RPM_BUILD_ROOT/usr/src
 cd $RPM_BUILD_ROOT/usr/src
@@ -156,36 +142,37 @@ cd $RPM_BUILD_ROOT/usr/src
 # Unpack the vanilla kernel sources
 bzip2 -cd %_sourcedir/linux-@SRCVERSION@.tar.bz2 \
 | tar xf -
-mv linux-@SRCVERSION@ linux-@SRCVERSION@.orig
 
-create_source_tree linux-$KERNELRELEASE
-%if %with_rt
-create_source_tree linux-$KERNELRELEASE-rt RT
-%endif
+mv linux-@SRCVERSION@ linux-$KERNELRELEASE$variant
+cd linux-$KERNELRELEASE$variant
 
-cat > %my_builddir/kernel-source.files <<EOF
+chmod -x arch/arm/mach-at91/board-yl-9200.c # executable by accident (fixed in 2.6.27)
+
+%_sourcedir/guards $variant_symbols %symbols < %_sourcedir/series.conf \
+    > .patches
+for patch in $(< .patches); do
+    if ! patch -s -F0 -E -p1 --no-backup-if-mismatch \
+	      -i %_builddir/@NAME@-@RPMVERSION@/$patch; then
+    echo "*** Patch $patch failed ***"
+    exit 1
+    fi
+done
+
+if [ -f %_sourcedir/localversion ] ; then
+    cat %_sourcedir/localversion > localversion
+fi
+
+cat > %my_builddir/@NAME@.files <<EOF
 %%%%defattr(-, root, root)
-%%%%ghost /usr/src/linux
-%%%%ghost /usr/src/linux-obj
-/usr/src/linux-$KERNELRELEASE
-/usr/src/linux-$KERNELRELEASE-obj
+%%%%ghost /usr/src/linux$variant
+%%%%ghost /usr/src/linux$variant-obj
+/usr/src/linux-$KERNELRELEASE$variant
+/usr/src/linux-$KERNELRELEASE$variant-obj
 /usr/share/doc/packages/%name
 /etc/rpm/macros.kernel-source
 /usr/lib/rpm/kernel-module-subpackage
+/lib/modules/*
 EOF
-
-%if %with_rt
-cat > %my_builddir/kernel-source-rt.files <<EOF
-%%%%defattr(-, root, root)
-%%%%ghost /usr/src/linux-rt
-%%%%ghost /usr/src/linux-rt-obj
-/usr/src/linux-$KERNELRELEASE-rt
-/usr/src/linux-$KERNELRELEASE-rt-obj
-/usr/share/doc/packages/%name
-/etc/rpm/macros.kernel-source
-/usr/lib/rpm/kernel-module-subpackage
-EOF
-%endif
 
 for config in $(%_sourcedir/guards %symbols < %_sourcedir/config.conf | grep -v vanilla); do
     arch=${config%/*}
@@ -203,26 +190,20 @@ for config in $(%_sourcedir/guards %symbols < %_sourcedir/config.conf | grep -v 
     case $flavor in
     (rt|rt_*)
 	set -- "$@" RT
-	source_tree=linux-$KERNELRELEASE-rt
-	echo "/lib/modules/$KERNELRELEASE-$flavor" >> %my_builddir/kernel-source-rt.files
-	;;
-    (*)
-	source_tree=linux-$KERNELRELEASE
-	echo "/lib/modules/$KERNELRELEASE-$flavor" >> %my_builddir/kernel-source.files
 	;;
     esac
 
-    diff -q $source_tree/.patches \
-	    <(%_sourcedir/guards $* %symbols < %_sourcedir/series.conf) \
-	|| continue
+    diff -q .patches \
+	 <(%_sourcedir/guards $* %symbols < %_sourcedir/series.conf) \
+       || continue
 
-    o=$RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE-obj/$arch/$flavor
+#    source_tree=linux-$KERNELRELEASE$variant
+    o=$RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE$variant-obj/$arch/$flavor
     mkdir -p $o
     cat $config \
-    | %_sourcedir/config-subst CONFIG_LOCALVERSION '"'-$flavor'"' \
+    | %_sourcedir/config-subst CONFIG_LOCALVERSION '"'-$RELEASE-$flavor'"' \
     | %_sourcedir/config-subst CONFIG_SUSE_KERNEL y \
     > $o/.config
-    echo "-$RELEASE" > $source_tree/localversion-rpm-release
 
     case $flavor in
     um)
@@ -238,39 +219,37 @@ for config in $(%_sourcedir/guards %symbols < %_sourcedir/config.conf | grep -v 
 %if %{tolerate_unknown_new_config_options}
     yes '' | make oldconfig $MAKE_ARGS
 %else
-    make -C $source_tree silentoldconfig $MAKE_ARGS < /dev/null
-    %_sourcedir/check-for-config-changes $config $o/.config
+    cp $o/.config $o/.config.before
+    make silentoldconfig $MAKE_ARGS < /dev/null
+    %_sourcedir/check-for-config-changes $o/.config.before $o/.config
+    rm -r $o/.config.before
 %endif
 
-    make -C $source_tree prepare $MAKE_ARGS
-    make -C $source_tree scripts $MAKE_ARGS
-    krel=$(make -C $source_tree -s kernelrelease $MAKE_ARGS)
+    make prepare $MAKE_ARGS
+    make scripts $MAKE_ARGS
+    krel=$(make -s kernelrelease $MAKE_ARGS)
     if [ $KERNELRELEASE != "${krel%%-*}" ]; then
 	echo "Kernel release mismatch: $KERNELRELEASE != ${krel%%-*}" >&2
 	exit 1
     fi
-    make -C $source_tree clean $MAKE_ARGS
+    make clean $MAKE_ARGS
 
     mkdir -p $RPM_BUILD_ROOT/lib/modules/$krel
-    ln -s ../../../usr/src/linux-$KERNELRELEASE \
+    ln -s ../../../usr/src/linux-$KERNELRELEASE$variant \
     	$RPM_BUILD_ROOT/lib/modules/$krel/source
 
     # Replace the absolute with a relative path
-    sed -e "s,$RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE,../../../linux-$KERNELRELEASE,g" \
+    sed -e "s,$RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE$variant,../../../linux-$KERNELRELEASE$variant,g" \
 	-i $o/Makefile
     rm -f $o/.config.old
 done
 
-rm -rf linux-@SRCVERSION@.orig
-rm -f linux-$KERNELRELEASE/.patches
-%if %with_rt
-rm -f linux-$KERNELRELEASE-rt/.patches
-%endif
+rm -f linux-$KERNELRELEASE$variant/.patches
 
 # Hardlink duplicate files automatically (from package fdupes).
 %fdupes $RPM_BUILD_ROOT
 
-cd $RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE-obj
+cd $RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE$variant-obj
 set -- *
 [ -e %_target_cpu ] || ln -s $1 %_target_cpu
 %ifarch ppc ppc64
@@ -280,17 +259,17 @@ set -- *
 
 cd $RPM_BUILD_ROOT/usr/src
 
-rm -f `find linux-$KERNELRELEASE -name ".gitignore"`
+rm -f `find linux-$KERNELRELEASE$variant -name ".gitignore"`
 
 # Remove $RPM_BUILD_ROOT prefix from symlinks.
-for link in $(find $RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE-obj -type l); do
+for link in $(find $RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE$variant-obj -type l); do
     target=$(readlink $link)
     rm -f $link
     ln -s ${target/$RPM_BUILD_ROOT/} $link
 done
 
-ln -sf linux linux  # dummy symlink
-ln -sf linux-obj linux-obj  # dummy symlink
+ln -sf linux$variant linux$variant  # dummy symlink
+ln -sf linux$variant-obj linux$variant-obj  # dummy symlink
 
 %install
 source .rpm-defs
@@ -300,7 +279,7 @@ DOC=$RPM_BUILD_ROOT/usr/share/doc/packages/%name
 mkdir -p $DOC
 cp %_sourcedir/README.SUSE $DOC
 ln -s /usr/share/doc/packages/%name/README.SUSE \
-    $RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE/
+    $RPM_BUILD_ROOT/usr/src/linux-$KERNELRELEASE$variant/
 
 install -m 755 -d $RPM_BUILD_ROOT/etc/rpm
 install -m 644 %_sourcedir/macros.kernel-source $RPM_BUILD_ROOT/etc/rpm/
@@ -308,30 +287,11 @@ install -m 755 -d $RPM_BUILD_ROOT/usr/lib/rpm
 install -m 644 %_sourcedir/kernel-module-subpackage \
     $RPM_BUILD_ROOT/usr/lib/rpm/
 
-for variant in '' '-rt'; do
-    (   cat %_sourcedir/functions.sh
-	sed -e "s:@KERNELRELEASE@:$KERNELRELEASE:g" \
-	    -e "s:@VARIANT@:$variant:g" \
-	    %_sourcedir/source-post.sh
-    ) > source-post$variant.sh
-done
+(   cat %_sourcedir/functions.sh
+    sed -e "s:@KERNELRELEASE@:$KERNELRELEASE:g" \
+	-e "s:@VARIANT@:$variant:g" \
+	%_sourcedir/source-post.sh
+) > @NAME@-post.sh
 
-%post -f source-post.sh
-
-%files -f kernel-source.files
-
-%package -n @NAME@-rt
-Summary:      Dummy summary
-License:      GPL
-Group:        Development/Sources
-Requires(post): coreutils sed
-Provides:       kernel-source-rt = @RPMVERSION@-%source_rel
-
-%description -n @NAME@-rt
-Dummy description.
-
-%post -n @NAME@-rt -f source-post-rt.sh
-
-%if %with_rt
-%files -n @NAME@-rt -f kernel-source-rt.files
-%endif
+%post -f @NAME@-post.sh
+%files -f @NAME@.files
