- kernel-binary.spec.in: Get rid of the braindead %build_nomodules hack:   instead of special casing kernel-ps3, check if CONFIG_MODULES is set   in the config file (as we already do in another place in the spec file).

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -24,7 +24,6 @@
 %define build_xen 0
 %define build_um 0
 %define build_vanilla 0
-%define build_nomodules 0
 
 %if %{build_flavor} == "kdump"
 %define build_kdump 1
@@ -37,9 +36,6 @@
 %endif
 %if %{build_flavor} == "vanilla"
 %define build_vanilla 1
-%endif
-%if %{build_flavor} == "ps3"
-%define build_nomodules 1
 %endif
 
 
@@ -467,21 +463,19 @@ ln -s initrd$suffix %buildroot/boot/initrd$suffix
 
 cp .config %buildroot/boot/config-$KERNELRELEASE
 
-%if ! %build_nomodules
-	make modules_install $MAKE_ARGS INSTALL_MOD_PATH=%buildroot
-%endif
-
-if ! %_sourcedir/check-supported-list \
-	%_sourcedir %buildroot/lib/modules/$KERNELRELEASE; then
-%if %supported_modules_check
-    exit 1
-%endif
-    echo "Consistency check error: please update supported.conf."
-fi
-
 gzip -c9 < Module.symvers > %buildroot/boot/symvers-$KERNELRELEASE.gz
 
-if grep -q '^CONFIG_MODULES=y$' .config; then
+if [ -n "$(source .config ; echo $CONFIG_MODULES)" ]; then
+    make modules_install $MAKE_ARGS INSTALL_MOD_PATH=%buildroot
+
+    if ! %_sourcedir/check-supported-list \
+	    %_sourcedir %buildroot/lib/modules/$KERNELRELEASE; then
+%if %supported_modules_check
+	exit 1
+%endif
+	echo "Consistency check error: please update supported.conf."
+    fi
+
     # Preserve exports from previous kernels when possible.
     old_symsets=%my_builddir/kabi/$SUBARCH/symsets-@FLAVOR@.tar.gz
     [ -e $old_symsets ] || old_symsets=
@@ -559,10 +553,11 @@ fi
 # later be installed in /usr/src/linux-@SRCVERSION@-%source_rel. Fix up the
 # build symlink.
 
-# need to fake modules directory to satisfy scripts
-%if %build_nomodules
-mkdir -p %buildroot/lib/modules/$KERNELRELEASE/
-%endif
+if [ -z "$(source .config ; echo $CONFIG_MODULES)" ]; then
+    # need to fake modules directory to satisfy scripts
+    # FIXME: Fix the scripts instead of adding ugly hacks ... !
+    mkdir -p %buildroot/lib/modules/$KERNELRELEASE/
+fi
 
 rm -f %buildroot/lib/modules/$KERNELRELEASE/{source,build}
 ln -s /usr/src/linux-${KERNELRELEASE%%-@FLAVOR@} \
