kernel-binary.spec.in: Emulate kabi.pl error when suse-kabi-tools is used

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -1301,6 +1301,8 @@ if [ %CONFIG_MODULES = y ]; then
                 %my_builddir/kabi/%cpu_arch/symtypes-%build_flavor \
                 %my_builddir/symtypes-%build_flavor || true
         %endif
+	# emulate kabi.pl so that kbuild can always find this message when kABI check fails
+	echo KABI: aborting due to kabi changes >&2
 
 	# %ignore_kabi_badness is defined in the Kernel:* projects in the
 	# OBS to be able to build the KOTD in spite of kabi errors
