- Add the kabi checker from SLES9. Update commonsyms and usedsyms.   Import reference modversions from the current Beta. Be very   tolerant with kabi changes so far.

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -52,6 +52,7 @@ Source32:     config-subst
 Source33:     check-for-config-changes
 Source34:     check-supported-list
 Source35:     install-configs
+Source36:     kabi-checks
 Source40:     build-source-timestamp
 Source41:     built-in-where
 Source42:     make-symsets
@@ -67,6 +68,7 @@ Source106:    patches.uml.tar.bz2
 Source107:    patches.xen.tar.bz2
 Source108:    patches.addon.tar.bz2
 Source109:    patches.kernel.org.tar.bz2
+Source120:    kabi.tar.bz2
 PreReq:       mkinitrd >= 1.2
 PreReq:       /usr/bin/test /bin/df /usr/bin/du /bin/cp /bin/sed /usr/bin/cut /usr/bin/expr /bin/touch
 BuildRoot:    %_tmppath/%name-%version-build
@@ -84,6 +86,7 @@ NoSource:     106
 NoSource:     107
 NoSource:     108
 NoSource:     109
+NoSource:     120
 
 # Provide the exported symbols as "ksym(symbol) = hash"
 %define __find_provides %_sourcedir/find-provides %name
@@ -99,7 +102,11 @@ NoSource:     109
 
 %define tolerate_unknown_new_config_options @TOLERATE_UNKNOWN_NEW_CONFIG_OPTIONS@
 
-%(chmod +x %_sourcedir/{arch-symbols,guards,config-subst,check-for-config-changes,check-supported-list,built-in-where,find-provides,make-symsets,find-types})
+# kABI change tolerance (default in maintenance should be 4, 8 or 15;
+# see scripts/kabi-checks)
+%define tolerate_kabi_changes 31
+
+%(chmod +x %_sourcedir/{arch-symbols,guards,config-subst,check-for-config-changes,check-supported-list,built-in-where,find-provides,make-symsets,find-types,kabi-checks})
 
 %description
 Dummy description.
@@ -120,7 +127,7 @@ symbols=$(
 echo "Architecture symbol(s):" $symbols
 
 # Unpack all sources and patches
-%setup -q -c -T -a 0 -a 100 -a 101 -a 102 -a 103 -a 104 -a 105 -a 106 -a 107 -a 108 -a 109
+%setup -q -c -T -a 0 -a 100 -a 101 -a 102 -a 103 -a 104 -a 105 -a 106 -a 107 -a 108 -a 109 -a 120
 
 # Generate the list of supported modules
 (   %_sourcedir/guards $symbols < %_sourcedir/supported.conf
@@ -376,6 +383,25 @@ fi
 # $(uname -m) to the ARCH directory.
 if [ ! -e %buildroot/$obj_dir/%_target_cpu ]; then
     ln -sf $SUBARCH %buildroot/$obj_dir/%_target_cpu
+fi
+
+# Check for kABI changes
+KABI=0
+if [ -e %my_builddir/kabi/$ARCH/@FLAVOR@ ]; then
+    %_sourcedir/kabi-checks \
+	%my_builddir/kabi/$ARCH/symvers-@FLAVOR@ \
+	Module.symvers \
+	%my_builddir/kabi/commonsyms \
+	%my_builddir/kabi/usedsyms \
+    || KABI=$?
+fi
+if [ $KABI -gt %tolerate_kabi_changes ]; then
+    echo "kABI changes of level $KABI not tolerable (max: %tolerate_kabi_changes), abort!"
+    echo "Please try to avoid the kABI changes."
+    echo "If this is not feasible, get permission to bump the kABI and check in"
+    echo "new reference files. If it's not for an official kernel, you may change"
+    echo "the value of %%tolerate_kabi_changes in rpm/kernel-binary.spec."
+    exit 1
 fi
 
 # We were building in %my_builddir/linux-@SRCVERSION@, but the sources will
