rpm/kernel-binary.spec.in: Adapt certificate handling for changes in v4.3

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -47,7 +47,7 @@
 
 # Define some CONFIG variables as rpm macros as well. (rpm cannot handle
 # defining them all at once.)
-%define config_vars CONFIG_MODULES CONFIG_MODULE_SIG CONFIG_KMSG_IDS CONFIG_SPLIT_PACKAGE CONFIG_SUSE_KERNEL_SUPPORTED CONFIG_EFI_STUB
+%define config_vars CONFIG_MODULES CONFIG_MODULE_SIG CONFIG_MODULE_SIG_KEY CONFIG_KMSG_IDS CONFIG_SPLIT_PACKAGE CONFIG_SUSE_KERNEL_SUPPORTED CONFIG_EFI_STUB
 %{expand:%(eval "$(test -n "%cpu_arch_flavor" && tar -xjf %_sourcedir/config.tar.bz2 --to-stdout config/%cpu_arch_flavor)"; for config in %config_vars; do echo "%%global $config ${!config:-n}"; done)}
 %define split_base (%CONFIG_SPLIT_PACKAGE == "y")
 %define split_extra (%CONFIG_SPLIT_PACKAGE == "y" && %CONFIG_SUSE_KERNEL_SUPPORTED == "y")
@@ -354,31 +354,27 @@ if test -e %my_builddir/kabi/%cpu_arch/symtypes-%build_flavor; then
     %_sourcedir/modversions --unpack . < $_
 fi
 
-# copy optional module signing files:
-# *.x509, *.crt
-#  - certificates with pubkeys used to verify module and firmware signatures
-#    at runtime. *.crt files assumed to be in the PEM format.
-# signing_key.priv
-#  - unencrypted private key used to sign modules and firmware during build
-# x509.genkey
-#  - openssl req config to generate a new signing_key.{x509,priv} pair for the
-#    build
-for f in %_sourcedir/*.x509 %_sourcedir/{signing_key.priv,x509.genkey}; do
-    if test -e "$f"; then
-        cp "$f" .
-    fi
-done
+# copy module signing certificate(s)
+found_sigkey=false
 for f in %_sourcedir/*.crt; do
     if ! test -e "$f"; then
         continue
     fi
-    out=${f##*/}
-    out=${out%.crt}.x509
-    openssl x509 -inform PEM -in "$f" -outform DER -out "$out"
+    if test "${f##*/}" = %CONFIG_MODULE_SIG_KEY; then
+        found_sigkey=true
+	cp "$f" .
+    else
+        cat "$f" >>keyring.crt
+    fi
 done
-# Convince kernel/Makefile not to generate a new keypair
-touch x509.genkey
-touch signing_key.x509
+if ! $found_sigkey; then
+    echo "warning: %CONFIG_MODULE_SIG_KEY not found"
+    # Let certs/Makefile generate a keypair
+    ../scripts/config --set-str CONFIG_MODULE_SIG_KEY "certs/signing_key.pem"
+fi
+if test -s keyring.crt; then
+    ../scripts/config --set-str SYSTEM_TRUSTED_KEYS_FILENAME "keyring.crt"
+fi
 
 MAKE_ARGS="$MAKE_ARGS %{?_smp_mflags}"
 
