- rpm/make-symsets: update to the latest version which will ignore   symset changes if the symset includes a symbol marked to be   ignored.

diff --git a/rpm/make-symsets b/rpm/make-symsets
--- a/rpm/make-symsets
+++ b/rpm/make-symsets
@@ -16,15 +16,19 @@ old_tarball=$2
 
 # Classify all the symbols by the directory they live in
 unset ${!class_*}
-while read class line; do
+while read class ignore line; do
     class=class_${class//[^a-zA-Z0-9_]/_}
     eval "$class[\${#$class[@]}]=\"$line\""
+    if [ $ignore -gt 0 ]; then
+	eval "ignore_$class=1"
+    fi
 done < <(
     awk '
     BEGIN { FS="\t" ; OFS="\t" }
     { class=$3
       sub(/\/[^/]+$/, "", class)
-      print class, $0
+      ignore=sub(/.*=>/, "", $1)
+      print class, ignore, $0
     }
     '
 )
@@ -71,18 +75,29 @@ if [ -n "$old_tarball" ]; then
 	[ $# -eq 1 ] || continue
 	newset=$1
 	# '*' doesn't occur in either file.
-	if [ -z "$( join -t '*' -j 1 -v 1 \
-			<(sort "$oldset") <(sort "$newset") )" ]; then
+	missing="$(join -t '*' -j 1 -v 1 <(sort "$oldset") <(sort "$newset"))"
+	if [ -z "$missing" ]; then
 	    keep_oldset[${#keep_oldset[@]}]=$oldset
 	    #echo "Provides: kernel($class) = ${oldset##*.} (old)"
 	else
-	    echo "No longer provided: kernel($class) = ${oldset##*.}" >&2
+	    set -- $(echo "$missing" | awk '{ print $2 "(" $1 ")" }')
+	    ignore=ignore_class_$class
+	    if [ -n "${!ignore}" ]; then
+		ignore="; ignoring"
+	    else
+		echo "Couldn't find ignore_$class"
+		status=1
+	    fi
+	    echo "No longer provided: kernel($class) = ${oldset##*.} (missing/changed: $@$ignore)" >&2
 	fi
     done
 
     if [ ${#keep_oldset[@]} -gt 0 ]; then
 	mv "${keep_oldset[@]}" $newdir/
     fi
+else
+    echo "No longer provided: previous kernel(...) symbols that may still be" \
+	 "compatible" >&2
 fi
 
 # Store the generated sets in $tarball
@@ -90,5 +105,7 @@ tar cf - -C $tmpdir/new $basename \
 | gzip -9 \
 > $tarball \
 || exit 1
+
+exit $status
 
 # vim:shiftwidth=4 softtabstop=4
