rpm: support compressed modules
Some of our scripts and scriptlets in rpm/ do not expect module files not
ending with ".ko" which currently leads to failure in preuninstall
scriptlet of cluster-md-kmp-default (and probably also other subpackages).

Let those which could be run on compressed module files recognize ".ko.xz"
in addition to ".ko".

diff --git a/rpm/modflist b/rpm/modflist
--- a/rpm/modflist
+++ b/rpm/modflist
@@ -5,6 +5,8 @@ output=$3
 mod_builtin=$4
 
 while read MOD ; do
-	[ -n "$MOD" ] || continue
-	cat $flist | grep /$MOD[.]ko\$ >> $output || { grep -q /$MOD[.]ko\$ $mod_builtin && echo Module $MOD built-in ;} || echo Module $MOD missing
-done < $modules
+    [ -n "$MOD" ] || continue
+    grep "/${MOD}\.ko\(\.xz\)\?\$" "$flist" >> "$output" \
+        || { grep -q "/${MOD}\.ko\(\.xz\)\?\$" $mod_builtin && echo "Module $MOD built-in"; } \
+        || echo Module "$MOD" missing
+done < "$modules"
