Add support for wildcards in supported.conf
- rpm/kernel-binary.spec.in: Generate Module.supported with all
  lines from supported conf, unsupported modules are marked as "no"
- rpm/split-modules: Use the supported flag in modules, instead of
  parsing the Module.supported file and report modules that have no
  supported marking.
- rpm/check-supported-list: Delete, this is done by split-modules
  now.

diff --git a/rpm/split-modules b/rpm/split-modules
--- a/rpm/split-modules
+++ b/rpm/split-modules
@@ -1,6 +1,6 @@
 #!/bin/bash
 # 
-# given a Module.supported, Module.base and modules.dep, generate list
+# given a Module.base and modules.dep, generate list
 # of base / supported / unsupported modules
 
 set -e
@@ -8,7 +8,7 @@ export LC_COLLATE=C
 
 usage()
 {
-	echo "Usage: ${0##*/} -b Module.base -s Module.supported [-d dir] [-i] [-o outdir]"
+	echo "Usage: ${0##*/} -b Module.base [-d dir] [-i] [-o outdir]"
 }
 
 options=$(getopt -o b:s:d:o:i -- "$@")
@@ -18,7 +18,6 @@ if test $? -ne 0; then
 fi
 eval set -- "$options"
 opt_base=
-opt_supp=
 opt_out=.
 opt_dir=.
 opt_ignore_errors=false
@@ -33,8 +32,6 @@ while test $# -gt 0; do
 	case "$opt" in
 	-b)
 		opt_base=$arg ;;
-	-s)
-		opt_supp=$arg ;;
 	-d)
 		opt_dir=$arg ;;
 	-o)
@@ -48,7 +45,7 @@ while test $# -gt 0; do
 		exit 1
 	esac
 done
-if test -z "$opt_base" -o -z "$opt_supp"; then
+if test -z "$opt_base"; then
 	usage >&2
 	exit 1
 fi
@@ -60,6 +57,28 @@ mkdir "$tmp/empty"
 find "$opt_dir" -type f -name '*.ko' -printf '/%P\n' | \
 	awk -F/ '{ n=$NF; gsub(/-/, "_", n); sub(/\.ko$/, "", n); print n " " $0; }' | \
 	sort >"$tmp/all"
+
+err=false
+while read mod path; do
+	support=$(/sbin/modinfo -F supported "$opt_dir/$path")
+	case "$support" in
+	yes | external)
+		echo "$mod"
+		;;
+	no)
+		;;
+	"")
+		echo "warning: $mod not listed in supported.conf" >&2
+		;;
+	*)
+		echo "error: invalid support flag for $mod: $support" >&2
+		err=true
+		;;
+	esac
+done <"$tmp/all" | sort -u >"$tmp/supp"
+if $err; then
+	exit 1
+fi
 
 modules_dep=$(find "$opt_dir" -type f -name modules.dep)
 if test -z "$modules_dep"; then
@@ -86,7 +105,6 @@ sed 'y/-/_/' <"$opt_base" | add_dependent_modules >"$tmp/base"
 join -j 1 -o 2.2 "$tmp/base" "$tmp/all" >"$opt_out/base-modules"
 
 # main
-sed 's/ .*//; y/-/_/' "$opt_supp" | sort -u >"$tmp/supp"
 add_dependent_modules "$tmp/supp-explain" <"$tmp/supp" >"$tmp/supp-all"
 if ! cmp -s "$tmp/supp" "$tmp/supp-all"; then
 	echo "The following unsupported modules are used by supported modules:" >&2
