scripts/cve_tools/kpm-bot: separate bugzilla content from build phase
bugzilla content is currently bound to build (resp. patch application)
phase currently which is not really ideal - especially when the content
needs to be regenerated. Introduce cve.completed file to reflect there
is nothing more to be done for the patch application/build and move the
bugzilla content creation into bugzilla action.

While at it also document differnt files.

Also realized that cve.failed should list the user branch if they fail
during build phase else we are not able to match those details easily.

diff --git a/scripts/cve_tools/kpm-bot b/scripts/cve_tools/kpm-bot
--- a/scripts/cve_tools/kpm-bot
+++ b/scripts/cve_tools/kpm-bot
@@ -12,6 +12,19 @@ LOG=~/kpm.log
 KSS_DASHBOARD='./scripts/cve_tools/kss-dashboard'
 LOCK_FILE=$PROCESS_DIR/.lock
 
+# List of files and transitions
+# cve.in - list of branches to process
+# 	+- cve.build - list of user branches with applied patches and pushed to repo
+#  		+- cve.ready - list of user branches which passed kbuild test
+#  		+- cve.failed - list of branches which failed to build
+# 	+- cve.failed - list of branches that failed to apply
+# cve.completed - cve has been completed and is ready for bugzilla handling
+# cve.details - details for bugzilla content (BRANCH detail per line)
+# cve.bugzilla - content to be sent to bugzilla
+# cve.bugzilla.done - contnet already sent to bugzilla
+# cve.in.done - processed list of branches to process
+# cve.build.done - processed build branches
+
 exec {LOCK_FD}>$LOCK_FILE
 
 exec > >(tee -a $LOG) 2>&1
@@ -134,13 +147,14 @@ check_incoming_queue()
 	local cve_file
 	for cve_file in $PROCESS_DIR/*.in
 	do
+		local cve="$(basename $cve_file .in)"
 		if [ ! -s "$cve_file" ]
 		then
 			mv $cve_file $cve_file.done
+			touch $PROCESS_DIR/${cve}.completed
 			continue
 		fi
 
-		local cve="$(basename $cve_file .in)"
 		local temp_failure=0
 		echo "=== $cve_file"
 		for target_branch in $(cat $cve_file)
@@ -240,10 +254,7 @@ check_incoming_queue()
 		# Nothing pushed and all failed to apply
 		if [ ! -s "$PROCESS_DIR/${cve}.build" ] && cmp "$PROCESS_DIR/${cve}.in.done" "$PROCESS_DIR/${cve}.failed" > /dev/null
 		then
-			local bugzilla_file=$PROCESS_DIR/$cve.bugzilla
-			echo "Fix failed to cleanly apply to all actionable branches:" > $bugzilla_file
-			print_status_with_details $PROCESS_DIR/${cve}.failed $cve >> $bugzilla_file
-
+			touch $PROCESS_DIR/$cve.completed
 		fi
 	done
 }
@@ -295,7 +306,6 @@ check_build_queue()
 		cve="$(basename $build_file .build)"
 
 		local pending=0
-		local existing_pr=0
 		local failed=""
 		echo "=== $cve"
 		for branch in $(cat $build_file)
@@ -328,7 +338,6 @@ check_build_queue()
 				continue
 			fi
 
-			let existing_pr++
 			if ! git rev-parse origin/$branch >/dev/null 2>&1
 			then
 				# Should not happen but should be recoverable
@@ -347,28 +356,43 @@ check_build_queue()
 				continue
 			elif [ $build_ret -eq 1 ]
 			then
-				echo "$branch failed through kbuild tests"
 				git push origin :$branch
 				git branch -D $branch
-				echo $base_branch >> $PROCESS_DIR/${cve}.failed
-				echo "$base_branch failed through kbuild tests" >> $PROCESS_DIR/${cve}.details
+				echo $branch >> $PROCESS_DIR/${cve}.failed
+				echo "$branch failed through kbuild tests" >> $PROCESS_DIR/${cve}.details
 				process_kbuild_report "$branch" >> $PROCESS_DIR/$cve.details
 			else
-				echo $branch >> $PROCESS_DIR/${cve}.ready
-				process_kbuild_report "$branch" >> $PROCESS_DIR/$cve.details
+				if ! grep -q $branch $PROCESS_DIR/${cve}.ready 2>/dev/null
+				then
+					echo $branch >> $PROCESS_DIR/${cve}.ready
+					process_kbuild_report "$branch" >> $PROCESS_DIR/$cve.details
+				fi
 			fi
 		done
 
 		[ $pending -eq 1 ] && continue
-		if [ $existing_pr -eq 0 ]
-		then
-			# Nothing left to do
-			cat $PROCESS_DIR/${cve}.build >> $PROCESS_DIR/${cve}.build.done
-			rm $PROCESS_DIR/${cve}.build
-			continue
-		fi
 
-		local bugzilla_file=$PROCESS_DIR/$cve.bugzilla
+		# Nothing left to do
+		cat $PROCESS_DIR/${cve}.build >> $PROCESS_DIR/${cve}.build.done
+		rm $PROCESS_DIR/${cve}.build
+		touch $PROCESS_DIR/$cve.completed
+	done
+}
+
+update_bugzilla()
+{
+	local update_bugzilla="$1"
+	local bugzilla_file
+	local ready_cve
+
+	echo "== Handle bugzilla files $update_bugzilla"
+
+	for ready_cve in $PROCESS_DIR/*.completed
+	do
+		local cve=$(basename $ready_cve .completed)
+		[ -s $PROCESS_DIR/$cve.bugzilla -o -s $PROCESS_DIR/$cve.bugzilla.done ] && continue
+
+		bugzilla_file=$PROCESS_DIR/$cve.bugzilla
 		if [ -s "$PROCESS_DIR/${cve}.ready" ]
 		then
 			echo "Fix for $cve apply cleanly and pass build test in:" > $bugzilla_file
@@ -381,18 +405,8 @@ check_build_queue()
 			echo "Fix for $cve FAILS for following branches:" >> $bugzilla_file
 			print_status_with_details $PROCESS_DIR/${cve}.failed $cve >> $bugzilla_file
 		fi
-
-		cat $PROCESS_DIR/${cve}.build >> $PROCESS_DIR/${cve}.build.done
-		rm $PROCESS_DIR/${cve}.build
 	done
-}
 
-update_bugzilla()
-{
-	local update_bugzilla="$1"
-	local bugzilla_file
-
-	echo "== Handle bugzilla files $update_bugzilla"
 	for bugzilla_file in $PROCESS_DIR/*.bugzilla
 	do
 		[ -s "$bugzilla_file" ] || continue
