scripts/check-patchfmt: New script to enforce a uniform patch format
In quilt refresh terms, it enforces -p ab --no-timestamps --no-index,
which is required to lower the number conflicts when different versions
of a patch. The order of the patched files (--sort) is not checked yet.

diff --git a/scripts/check-patch b/scripts/check-patch
--- a/scripts/check-patch
+++ b/scripts/check-patch
@@ -98,6 +98,19 @@ while :; do
     esac
 done
 
+# We might be called via a symlink in .git/hooks
+for f in scripts/check-patchfmt ../scripts/check-patchfmt ${0%/*}/check-patchfmt
+do
+	if test -x "$f"; then
+		check2=$f
+		break
+	fi
+done
+if test -z "$check2"; then
+	echo "Warning: could not find scripts/check-patchfmt" >&2
+	check2=:
+fi
+
 bad=0
 if $stdin; then
     case $# in
@@ -116,6 +129,9 @@ if $stdin; then
     trap "rm -f $content" EXIT
     cat >"$content"
     check_patch "$filename" "$content"
+    if ! $check2 --stdin "$filename" <"$content" && ! $relaxed; then
+	    bad=2
+    fi
 else
     if test $# -eq 0; then
         echo "No patches given" >&2
@@ -124,10 +140,13 @@ else
     fi
     for filename in "$@"; do
         check_patch "$filename" "$filename"
+	if ! $check2 "$filename" && ! $relaxed; then
+		bad=2
+	fi
     done
 fi
 
-if test $bad -gt 0; then
+if test $bad -eq 1; then
     echo "For more information, see the Patch Headers chapter in the README file." >&2
 fi
 
