scripts/check-kernel-fix: make the whole state handling sha specific
rename those functions to make the review easier. No function change is
intended here.

diff --git a/scripts/check-kernel-fix b/scripts/check-kernel-fix
--- a/scripts/check-kernel-fix
+++ b/scripts/check-kernel-fix
@@ -84,17 +84,21 @@ git_fixes_sha="$tmpdir/git_fixes_sha"
 git_fixes_output="$tmpdir/git_fixes_output"
 git_fixes_pid=0
 
-branch_state_file()
+branch_state_sha_file()
 {
 	local branch=$1
-	echo $tmpdir/branch-state.$(echo $branch | sed 's@/@_@g')
+	local sha=$2
+
+	[ -z "$sha" ] && fail "sha missing"
+	echo $tmpdir/branch-state.$(echo $branch | sed 's@/@_@g').$sha
 }
 
-set_branch_state()
+set_branch_sha_state()
 {
     local branch=$1
-    local state=$2
-    local branch_file="$(branch_state_file $branch)"
+    local sha=$2
+    local state=$3
+    local branch_file="$(branch_state_sha_file $branch $sha)"
 
     echo "$state" > $branch_file
 }
@@ -146,7 +150,7 @@ handle_patch_present()
     then
             if git grep -qi "^References:.*$cve\>" origin/$branch
             then
-                    set_branch_state $branch "$sha:ok_reference_present"
+                    set_branch_sha_state $branch $sha "ok_reference_present"
                     return 0
             fi
     fi
@@ -163,11 +167,11 @@ handle_patch_present()
 		done
 
 		if [ -n "$missing_references" ] ; then
-		    set_branch_state $branch "$sha:ok_missing_references:$missing_references $patch"
+		    set_branch_sha_state $branch $sha "ok_missing_references:$missing_references $patch"
 		    return 0
 		fi
 	fi
-	set_branch_state $branch "$sha:ok_commit_present"
+	set_branch_sha_state $branch $sha "ok_commit_present"
 	return 0
     fi
 
@@ -188,7 +192,7 @@ handle_cve_blacklisted()
     if [ -n "$blacklist_entry" ]
     then
 	    local blacklist_reason="$(echo $blacklist_entry | sed 's@^[a-f0-9]\+[[:space:]]#[[:space:]]*@@')"
-	    set_branch_state $branch "$sha:blacklisted $blacklist_reason"
+	    set_branch_sha_state $branch $sha "blacklisted $blacklist_reason"
 	    return 0
     fi
 
@@ -198,6 +202,7 @@ handle_cve_blacklisted()
 handle_parent_inheritable_state()
 {
     local branch=$1
+    local sha=$2
 
     # Check parent branches are ok then nothing to be checked for this one
     # Disable the heuristic for the verbose mode where we want to see all
@@ -207,11 +212,11 @@ handle_parent_inheritable_state()
 	    local merge_branch=
 	    for merge_branch in $(print_merge_branches $branches_conf $branch)
 	    do
-		    local merge_branch_file="$(branch_state_file $merge_branch)"
+		    local merge_branch_file="$(branch_state_sha_file $merge_branch $sha)"
 		    wait_for_file "$merge_branch_file"
-		    if grep "$sha:ok_" "$merge_branch_file" >/dev/null 2>&1
+		    if grep "ok_" "$merge_branch_file" >/dev/null 2>&1
 		    then
-			    set_branch_state $branch "$sha:ok_will_merge"
+			    set_branch_sha_state $branch $sha "ok_will_merge"
 			    return 0
 		    fi
 	    done
@@ -232,7 +237,7 @@ check_for_warnings()
     local branch="$1"
     local conf_file_map="$2"
     local sha=$3
-    local warn_file="$(branch_state_file $branch).warns"
+    local warn_file="$(branch_state_sha_file $branch $sha).warns"
     shift 3
 
     check_config "$branch" "$conf_file_map" "$@" >> $warn_file
@@ -243,7 +248,9 @@ check_for_warnings()
 
 has_warnings()
 {
-    local warn_file="$(branch_state_file $branch).warns"
+    local branch=$1
+    local sha=$2
+    local warn_file="$(branch_state_sha_file $branch $sha).warns"
 
     test -s $warn_file
 }
@@ -251,7 +258,8 @@ has_warnings()
 print_warnings()
 {
     local branch=$1
-    local warn_file="$(branch_state_file $branch).warns"
+    local sha=$2
+    local warn_file="$(branch_state_sha_file $branch $sha).warns"
 
     cat $warn_file
 }
@@ -289,7 +297,7 @@ EOF
 
 # Check state of the given branch wrt to given sha, its fixes and references
 #
-# The outcome is recorded via set_branch_state and the following states are
+# The outcome is recorded via set_branch_sha_state and the following states are
 # possible
 #
 #   + nope_cvss: doesn't qualify based on the CVSS scoring
@@ -313,7 +321,7 @@ EOF
 # files[]: only used for {maybe_}missing_commit to check kernel configs
 #
 # Side effects:
-# set_branch_state called with appropriate action
+# set_branch_sha_state called with appropriate action
 check_branch_state()
 {
     local branch="$1"
@@ -333,17 +341,17 @@ check_branch_state()
 		    handle_patch_present $branch $sha $references && return
 		    handle_cve_blacklisted $branch $sha $cve && return
 	    fi
-	    set_branch_state $branch "$sha:nope_cvss"
+	    set_branch_sha_state $branch $sha "nope_cvss"
 	    return
     fi
 
-    handle_parent_inheritable_state $branch
+    handle_parent_inheritable_state $branch $sha
 
     local base=$(branch_base_ver $branch)
 
     # Already merged upstream?
     if sha_merged_in_upstream_tag "$sha" "$base" ; then
-	set_branch_state $branch "$sha:nope_commit_in_base"
+	set_branch_sha_state $branch $sha "nope_commit_in_base"
 	return
     fi
 
@@ -357,17 +365,17 @@ check_branch_state()
 	local affected="$(affected_by_git_fixes "$branch" "$base" $fixes)"
 
 	if [ -n "$affected" ] ; then
-	    set_branch_state $branch "$sha:missing_commit:$affected"
+	    set_branch_sha_state $branch $sha "missing_commit:$affected"
 	    check_for_warnings "$branch" "$conf_file_map" $sha "${files[@]}"
 	else
-	    set_branch_state $branch "$sha:nope_unaffected"
+	    set_branch_sha_state $branch $sha "nope_unaffected"
 	fi
 
 	return
     fi
 
     # missing git fixes
-    set_branch_state $branch "$sha:maybe_missing_commit:$ref"
+    set_branch_sha_state $branch $sha "maybe_missing_commit:$ref"
 
     check_for_warnings "$branch" "$conf_file_map" $sha "${files[@]}"
 }
@@ -380,7 +388,7 @@ check_blacklisted_in_parent()
 
     for merge_branch in $(print_merge_branches $branches_conf $branch)
     do
-	    local merge_branch_file="$(branch_state_file $merge_branch)"
+	    local merge_branch_file="$(branch_state_sha_file $merge_branch $sha)"
 	    if grep -E "$sha:blacklisted" "$merge_branch_file" >/dev/null 2>&1
 	    then
 		    echo -e "\tWW $merge_branch blacklisted ${sha}. Unless $branch differs then you can ignore this."
@@ -415,7 +423,7 @@ __print_action()
 	echo $*
 }
 
-# Prints action for the given branch
+# Prints action for the given branch and sha
 # Globals
 # verbose_mode: only {maybe_}missing_patch are printed if this is empty
 # warning_only_mode: only prints actions if there are warnings associated. This
@@ -424,7 +432,7 @@ __print_action()
 #
 # Side effects:
 # creates $affected_file if the branch is affected
-print_action()
+print_sha_action()
 {
     local branch="$1"
     local sha="$2"
@@ -438,19 +446,19 @@ print_action()
 	missing_commit)
 	    eligible_braches=$(($eligible_braches+1))
 	    __print_action "$branch: MANUAL: backport $sha ($references)"
-	    has_warnings $branch && branches_with_warnings=$(($branches_with_warnings+1))
-	    print_warnings $branch
+	    has_warnings $branch $sha && branches_with_warnings=$(($branches_with_warnings+1))
+	    print_warnings $branch $sha
 	    ;;
 
 	maybe_missing_commit)
 	    eligible_braches=$(($eligible_braches+1))
 	    if [ $warning_only_mode -eq 1 ]
 	    then
-		    has_warnings $branch || return 0
+		    has_warnings $branch $sha || return 0
 	    fi
 	    branches_with_warnings=$(($branches_with_warnings+1))
 	    __print_action "$branch: MANUAL: might need backport of $sha ($references)"
-	    print_warnings $branch
+	    print_warnings $branch $sha
 	    ;;
 
 	ok_missing_references)
@@ -471,12 +479,13 @@ print_action()
 find_and_print_toplevel_actions()
 {
     local branch="$1"
-    local flat_mode=$2
-    local branch_file="$(branch_state_file $branch)"
+    local sha=$2
+    local flat_mode=$3
+    local branch_file="$(branch_state_sha_file $branch $sha)"
 
     if [ "$flat_mode" -eq 1 ]
     then
-	    print_action $branch $(sed 's@:@ @g' $branch_file)
+	    print_sha_action $branch $sha $(sed 's@:@ @g' $branch_file)
 	    return
     fi
 
@@ -489,13 +498,13 @@ find_and_print_toplevel_actions()
     # are printed in a proper ordering
     local merge_branch=
     for merge_branch in $(print_merge_branches $branches_conf $branch) ; do
-	    local merge_branch_file="$(branch_state_file $merge_branch)"
+	    local merge_branch_file="$(branch_state_sha_file $merge_branch $sha)"
 	    local mb_state=$(cut -d: -f2 $merge_branch_file)
 
 	    [[ ! "$mb_state" =~ nope* && "$mb_state" != "blacklisted" ]] && return
     done
 
-    print_action $branch $(sed 's@:@ @g' $branch_file)
+    print_sha_action $branch $sha $(sed 's@:@ @g' $branch_file)
 }
 
 print_maintainer_info()
@@ -528,9 +537,9 @@ print_maintainer_info()
 # files: array of files touched by the sha
 handle_single_sha()
 {
-	# TODO sha should be local?
-	sha=$1
-	local branch=$2
+	local sha=$1
+	local cve="$2"
+	local branch=$3
 
 	local git_fixes=
 	# Handle in patch and provided git fixes
@@ -567,18 +576,18 @@ handle_single_sha()
 	# TODO do we print actions per sha or per branch?
 	if [ -n "$branch" ]
 	then
-		branch_file="$(branch_state_file $branch)"
+		branch_file="$(branch_state_sha_file $branch $sha)"
 
 		single_branch_mode=1
 		# We have an explicit branch to check
 		check_branch_state $branch "$sha" "$git_fixes" "$cvss" $references
-		print_action $branch $(sed 's@:@ @g' $branch_file)
+		print_sha_action $branch $sha $(sed 's@:@ @g' $branch_file)
 	else
 		# Check state of each branch
 		single_branch_mode=0
 		for_each_build_branch_paralel "$branches_conf" check_branch_state "$sha" "$git_fixes" "$cvss" $references
 
-		for_each_build_branch "$branches_conf" find_and_print_toplevel_actions $flat_mode
+		for_each_build_branch "$branches_conf" find_and_print_toplevel_actions $sha "$flat_mode"
 	fi
 
 	[ $eligible_braches -gt 0 -a $eligible_braches -eq $branches_with_warnings ] &&  echo "All eligible branches have warnings. If they are correct then there is NO ACTION NEEDED for $sha"
@@ -681,7 +690,7 @@ then
 	git_fixes_pid=$!
 fi
 
-handle_single_sha $sha $2
+handle_single_sha $sha "$cve" $2
 
 # Final conclusion shared for all shas
 if [ ! -e "$actions_file" ]
