scripts/check-kernel-fix: print CVE info before sha
this is a preparatory work to allow a single CVE to refer to multiple
commits.

diff --git a/scripts/check-kernel-fix b/scripts/check-kernel-fix
--- a/scripts/check-kernel-fix
+++ b/scripts/check-kernel-fix
@@ -585,6 +585,14 @@ else
 fi
 
 [ -z "$cve" ] && cve=$(sha2cve $sha $refresh)
+if [ -n "$cve" ]
+then
+	[ -z "$bsc" ] && bsc=$(cve2bugzilla $cve $refresh)
+	[ -z "$cvss" ] && cvss=$(cve2cvss $cve $refresh)
+	echo "Security fix for $cve ${bsc:-bsc unknown} with CVSS ${cvss:-unknown}"
+	is_cve_rejected $cve && echo "W: $cve has been rejected" >&2
+	[ -z "$cvss" -o -z "$bsc" ] && fail "Incomplete references re-check with -r or use -s/-b to specify missing references"
+fi
 
 # Handle in patch and provided git fixes
 if [ -n "$enforce_expl_fixes" ]
@@ -596,15 +604,6 @@ fi
 [ -n "$expl_fixes" ] && git_fixes="$git_fixes $expl_fixes"
 
 print_upstream_sha_summary $sha "$git_fixes"
-
-if [ -n "$cve" ]
-then
-	[ -z "$bsc" ] && bsc=$(cve2bugzilla $cve $refresh)
-	[ -z "$cvss" ] && cvss=$(cve2cvss $cve $refresh)
-	echo "Security fix for $cve ${bsc:-bsc unknown} with CVSS ${cvss:-unknown}"
-	is_cve_rejected $cve && echo "W: $cve has been rejected" >&2
-	[ -z "$cvss" -o -z "$bsc" ] && fail "Incomplete references re-check with -r or use -s/-b to specify missing references"
-fi
 
 if [ $maintainers -eq 1 -a -x $SUSE_GET_MAINTAINERS ]
 then
