scripts/check-kernel-commit: Report blacklisted terms
The blacklist hides the commit for tools reporting candidates
for backporting. It might hide commits which might get important
later.

Anyway, the fact that they are blacklisted is interesting and
it would be nice when check-kernel-commit report them.

Signed-off-by: Petr Mladek <pmladek@suse.com>

diff --git a/scripts/check-kernel-commit b/scripts/check-kernel-commit
--- a/scripts/check-kernel-commit
+++ b/scripts/check-kernel-commit
@@ -94,6 +94,7 @@ check_branch()
     local branch="$1"
     git show-ref --verify --quiet "refs/remotes/origin/${branch}" || return 2
     local found=""
+    local blacklisted=""
     local missing=""
     local term
     for term in $KBC_CHECK_TERMS ; do
@@ -108,30 +109,51 @@ check_branch()
         if [ $? -eq 0 ] ; then
             found="$found $term"
         else
-            missing="$missing $term"
+	    git grep -qi "$term" "remotes/origin/$branch" -- 'blacklist.conf' 2>/dev/null
+	    if [ $? -eq 0 ] ; then
+		blacklisted="$blacklisted $term"
+	    else
+		missing="$missing $term"
+	    fi
         fi
     done
 
     # found
-    if [ -z "$missing" ] ; then
+    if [ -z "$missing" ] && [ -z "$blacklisted" ] ; then
         return 0
     fi
 
+    # blacklisted
+    if [ -z "$found" ] && [ -z "$missing" ] ; then
+        return 1
+    fi
+
     # missing
-    if [ -z "$found" ] ; then
-        return 2
+    if [ -z "$found" ] && [ -z "$blacklisted" ] ; then
+        return 3
     fi
 
     # partly
     if [ $verbose -ne 0 ] ; then
-        echo "        missing hash:"
-        local hash
-        for hash in $missing ; do
-            echo "                $hash"
-        done
+	if [ -n "$missing" ] ; then
+            echo "        missing hash:"
+            local hash
+            for hash in $missing ; do
+		echo "                $hash"
+            done
+	fi
+
+	if [ -n "$blacklisted" ] ; then
+            echo "        blacklisted hash:"
+            local hash
+            for hash in $blacklisted ; do
+		echo "                $hash"
+            done
+	fi
+
         echo
     fi
-    return 1
+    return 2
 }
 
 check_parents()
@@ -187,6 +209,9 @@ while read line ; do
             echo "<ok>"
             ;;
         1)
+            echo "<blacklisted>"
+            ;;
+        2)
             echo -n "<partly> "
             check_parents $parents
             # print missing commits
