- Avoid redundant output that scripts/check-conf already reports.

diff --git a/scripts/check-cvs-add b/scripts/check-cvs-add
--- a/scripts/check-cvs-add
+++ b/scripts/check-cvs-add
@@ -28,7 +28,13 @@ not_in_cvs="$(
     ) | sort | uniq -u)"
     
 if [ -n "$not_in_cvs" ]; then
-    echo "$not_in_cvs" \
-    | sed -e "s,^,Not in CVS: ," >&2
+    for patch in $not_in_cvs; do
+	if [ -e "$patch" ]; then
+	    echo "Not in CVS: $patch" >&2
+	else
+	    # scripts/check-conf already reports missing patches:
+	    : #echo "Missing: $patch" >&2
+	fi
+    done
     exit 1
 fi
