- scripts/check-kernel-fix: Handled unknown branches more gracefully - scripts/common-functions:
This doesn't happen often. Usually when branches.conf doesn't match the
kernel-source.git tree because of renaming. git fetch should fix those
so be more helpuful to poor users.

diff --git a/scripts/common-functions b/scripts/common-functions
--- a/scripts/common-functions
+++ b/scripts/common-functions
@@ -142,7 +142,7 @@ fail()
 branch_base_ver()
 {
     local branch="origin/$1"
-    git show-ref --verify --quiet "refs/remotes/${branch}" || fail "$branch invalid branch"
+    git show-ref --verify --quiet "refs/remotes/${branch}" || fail "$branch invalid branch. Please git fetch origin."
 
     local base_ver="v$(git grep SRCVERSION $branch -- rpm/config.sh | sed 's@.*=@@')"
 
@@ -281,7 +281,7 @@ sha_to_patch_in_branch()
     [ -z "$sha" ] && fail "sha_to_patch_in_branch: No sha provided"
     [ -z "$branch" ] && fail "sha_to_patch_in_branch: No branch provided"
 
-    branch_file=$(git --no-pager grep -l -i "^git-commit[[:space:]]*:[[:space:]]*$sha" "origin/$branch")
+    branch_file=$(git --no-pager grep -l -i "^git-commit[[:space:]]*:[[:space:]]*$sha" "origin/$branch" 2>/dev/null )
 
     echo "${branch_file#origin/$branch:}"
 }
