scripts/common-functions: allow both branch and origin/branch for git queries

diff --git a/scripts/common-functions b/scripts/common-functions
--- a/scripts/common-functions
+++ b/scripts/common-functions
@@ -156,7 +156,7 @@ check_config()
 	while read conf
 	do
 		conf_num=$(($conf_num+1))
-		if ! git grep -qiE "$conf=(y|m)" origin/$branch -- config
+		if ! git grep -qiE "$conf=(y|m)" origin/${branch#origin/} -- config
 		then
 			echo -e "\tWW $conf not enabled."
 			failed=$(($failed+1))
@@ -268,10 +268,10 @@ fail()
 
 branch_base_ver()
 {
-    local branch="origin/$1"
-    git show-ref --verify --quiet "refs/remotes/${branch}" || fail "$branch invalid branch. Please git fetch origin."
+    local branch="$1"
+    git show-ref --verify --quiet "refs/remotes/origin/${branch#origin/}" || fail "$branch invalid branch. Please git fetch origin."
 
-    local base_ver="v$(git grep SRCVERSION $branch -- rpm/config.sh | sed 's@.*=@@')"
+    local base_ver="v$(git grep SRCVERSION origin/${branch#origin/} -- rpm/config.sh | sed 's@.*=@@')"
 
     echo $base_ver
 }
@@ -412,7 +412,7 @@ sha_to_patch_in_branch()
     [ -z "$sha" ] && fail "sha_to_patch_in_branch: No sha provided"
     [ -z "$branch" ] && fail "sha_to_patch_in_branch: No branch provided"
 
-    branch_file=$(git --no-pager grep -l -i -E "^(git|alt)-commit[[:space:]]*:[[:space:]]*$sha" "origin/$branch" -- 'patches.*' 2>/dev/null )
+    branch_file=$(git --no-pager grep -l -i -E "^(git|alt)-commit[[:space:]]*:[[:space:]]*$sha" "origin/${branch#origin/}" -- 'patches.*' 2>/dev/null )
 
     echo "${branch_file#origin/$branch:}"
 }
@@ -451,5 +451,5 @@ patch_has_reference_in_branch()
     [ -z "$ref" ] && fail "patch_has_reference_in_branch: No reference provided"
     [ -z "$branch" ] && fail "patch_has_reference_in_branch: No branch provided"
 
-    git --no-pager grep -w -q -i "^references:.*$ref" "origin/$branch" -- "$patch"
+    git --no-pager grep -w -q -i "^references:.*$ref" "origin/${branch#origin/}" -- "$patch"
 }
