- Fix for :ext:user@host:/repository entries in CVS/Root.

diff --git a/scripts/cvs-wd-timestamp b/scripts/cvs-wd-timestamp
--- a/scripts/cvs-wd-timestamp
+++ b/scripts/cvs-wd-timestamp
@@ -59,7 +59,24 @@ query_timestamp() {
 	EOF
 }
 
-IFS=: read server cvsroot < CVS/Root
+# Various forms of CVS/Root entries exist:
+#   :ext:user@host:/repository
+#   :pserver:user@host:/repository
+#   user@host:/repository
+cvsroot=$(cat CVS/Root)
+case "$cvsroot" in
+:ext:*)
+    cvsroot=${cvsroot#:ext:}
+#:pserver:*)
+#    cvsroot=${cvsroot#:pserver:}
+esac
+set -- $(IFS=: ; echo $cvsroot)
+server=$1 cvsroot=$2
+if [ -z "$server" -o -z "$cvsroot" ]; then
+    echo "Failed to parse CVS/Root" >&2
+    exit 1
+fi
+
 read repository < CVS/Repository
 set -- $(${CVS_RSH:-rsh} -q $server "$(query_timestamp)")
 # echo "$@"
