scripts/git-commit-msg: Count changed references globally, not per file
Per-file counting would be too strict in requirement on commit message
since it would miss source file of a possible rename.

diff --git a/scripts/git-commit-msg b/scripts/git-commit-msg
--- a/scripts/git-commit-msg
+++ b/scripts/git-commit-msg
@@ -25,23 +25,16 @@ git_dir=$(git rev-parse --git-dir)
 test -f "$git_dir/MERGE_HEAD" && exit
 
 err=0
-git diff-index --name-status --diff-filter=AM --cached HEAD | (
-while read stat file garbage; do
-    case "$file" in
-    patches.*/*)
-        new_refs=$(git diff-index -p --cached HEAD "$file" | \
-                   awk -v FPAT='[^, ]+' \
-                       '/^+References:/ {for (i=2; i <= NF; i++) refs[$i]++}
-                        /^-References:/ {for (i=2; i <= NF; i++) refs[$i]--}
-                        END { for (r in refs) if (refs[r] > 0) print(r)}')
-        for ref in $new_refs ; do
-            grep -q $ref $commit_file || { echo "New reference '$ref' missing in the commit message." ; err=1 ; }
-        done
-        ;;
-    esac
+new_refs=$(git diff-index -p --cached HEAD "patches.*/*" | \
+	   awk -v FPAT='[^, ]+' \
+	       '/^+References:/ {for (i=2; i <= NF; i++) refs[$i]++}
+		/^-References:/ {for (i=2; i <= NF; i++) refs[$i]--}
+		END { for (r in refs) if (refs[r] > 0) print(r)}')
+for ref in $new_refs ; do
+    grep -q $ref $commit_file || { echo "New reference '$ref' missing in the commit message." ; err=1 ; }
 done
 
 if test "$err" != 0; then
     echo "Aborting."
     exit "$err"
-fi ) || exit
+fi
