- Add code for parsing build log files (/work/built/mbuild/$job/$dist/Logfile.*)   so that ABI changes can be ignored directly from there instead of having to   build another set of packages first.

diff --git a/scripts/ignore-kabi-changes b/scripts/ignore-kabi-changes
--- a/scripts/ignore-kabi-changes
+++ b/scripts/ignore-kabi-changes
@@ -38,25 +38,68 @@ trap "rm -rf $tmpdir" EXIT
 shopt -s nullglob
 
 archs_flavors="$(scripts/guards --list < config.conf)"
-for rpm in "$@"; do
-    case "$rpm" in
+for file in "$@"; do
+    case "${file##*/}" in
 	*.src.rpm | *.nosrc.rpm | *.delta.rpm)
+	    continue
+	    ;;
+	*.rpm | Logfile.*)
+	    ;;
+	*)
+	    echo "Cannot guess file type from filename $file; skipping" >&2
 	    continue
 	    ;;
     esac
 
     # There may be symlinks and regular files. Skip duplicates.
-    for file in "${files_processed[@]}"; do
-	[ "$rpm" -ef "$file" ] && continue 2
+    for file2 in "${files_processed[@]}"; do
+	[ "$file" -ef "$file2" ] && continue 2
     done
-    files_processed[${#files_processed[@]}]=$rpm
+    files_processed[${#files_processed[@]}]=$file
 
-    exec 3< <(rpm -qp --qf '%{NAME}\n%{ARCH}\n%{VERSION}\n%{RELEASE}' "$rpm")
-    read name <&3
-    read arch <&3
-    read version <&3
-    read release <&3
-    exec 3<&-
+    case "${file##*/}" in
+	*.rpm)
+	    exec 3< <(rpm -qp --qf '%{NAME}\n%{ARCH}\n%{VERSION}\n%{RELEASE}' "$file")
+	    read name <&3
+	    read arch <&3
+	    read version <&3
+	    read release <&3
+	    exec 3<&-
+
+	    rpm2cpio "$file" \
+	    | ( cd $tmpdir && cpio -dim --quiet './boot/symvers-*' )
+
+	    set -- $tmpdir/boot/symvers-*
+	    if [ $# -ne 1 ]; then
+		echo "Only one /boot/symvers-* file expected in $file; skipping" >&2
+		continue
+	    fi
+	    new_syms="$(zcat "$1")"
+	    ;;
+	Logfile.*)
+	    name=$(cat "$file" \
+		   | sed -ne 's/^----- building \(.*\)\.spec.*/\1/p')
+	    dist=$(cat "$file" | sed -ne 's/^Building for \([^ ]*\)$/\1/p')
+	    arch=${dist##*-}
+	    version=$(cat "$file" | sed -ne 's/^> Version: *//p')
+	    release=$(cat "$file" | sed -ne 's/^> Release: *//p')
+
+	    if [ -z "$name" -o -z "$arch" ]; then
+		echo "[$name]"
+		echo "[$arch]"
+		echo "Could not determine package name and architecture from $file; skipping" >&2
+		continue
+	    fi
+
+	    new_syms="$(cat "$file" \
+		        | sed -ne 's/^Warning: .*: .*(0x[0-9a-zA-Z]*) changed to \(.*\)(\(0x[0-9a-zA-Z]*\)).*/\2 \1/p')"
+
+	    if [ -z "$new_syms" ]; then
+		echo "No ABI changes found in $file; skipping" >&2
+		continue
+	    fi
+	    ;;
+    esac
 
     build_arch=$arch
     case "$arch" in
@@ -74,7 +117,7 @@ for rpm in "$@"; do
 	source | syms)
 	    ;;
 	*)
-	    echo "${rpm%%*/}: not a known arch/flavor; skipping $rpm" >&2
+	    echo "${rpm%%*/}: not a known arch/flavor; skipping $file" >&2
 	    ;;
 	esac
 	continue
@@ -84,25 +127,15 @@ for rpm in "$@"; do
 
     symvers=kabi/$arch/symvers-$flavor
     if [ ! -e $symvers ]; then
-	echo "File $symvers not found; skipping $rpm" >&2
+	echo "File $symvers not found; skipping $file" >&2
 	continue
     fi
-
-    rpm2cpio "$rpm" \
-    | ( cd $tmpdir && cpio -dim --quiet './boot/symvers-*' )
-
-    set -- $tmpdir/boot/symvers-*
-    if [ $# -ne 1 ]; then
-	echo "Only one /boot/symvers-* file expected in $rpm; skipping" >&2
-	continue
-    fi
-    new_symvers=$1
 
     awk -f <(
 	echo "BEGIN {"
 	echo $'\tsymvers="'$symvers'"'
 	echo $'\tOFS="\t"'
-	zcat $new_symvers \
+	echo "$new_syms" \
 	| sed -nre 's:^(0x[a-fA-Z0-9]+)[ \t]+([^ \t]+).*:\tsymver["\2"]="\1":p'
 	echo "}"
 	echo '
@@ -121,9 +154,6 @@ for rpm in "$@"; do
 	'
 	) $symvers > $symvers.new
     [ $? = 0 ] || continue
-    if [ -z "$dry_run" ]; then
-	mkdir ${symvers%/*}
-	mv $symvers.new $symvers
-    fi
+    [ -z "$dry_run" ] && mv $symvers.new $symvers
     rm -rf $tmpdir/boot
 done
