- scripts/check-cvs-add, scripts/check-patch,   scripts/cvs-touched-files, scripts/cvs-wd-timestamp, scripts/log,   scripts/tar-up.sh, scripts/wd-functions.sh: delete cvs-related   stuff, make the scripts work also outside a git working directory   (no waranty). - scripts/newest-timestamp: Delete. - scripts/tag-snapshot: Delete.

diff --git a/scripts/log b/scripts/log
--- a/scripts/log
+++ b/scripts/log
@@ -4,6 +4,11 @@
 
 . ${0%/*}/wd-functions.sh
 
+if ! $using_git; then
+    echo "ERROR: not in a git working directory."
+    exit 1
+fi
+
 scripts/check-cvs-add || exit 1
 
 CHANGES=kernel-source.changes
@@ -117,15 +122,11 @@ if $VC $CHANGES $message; then
 	read yesno && \
 	case "$yesno" in
 	    "" | [yY] | yes)
-                if $using_cvs; then
-                    cvs -z3 commit -F $message
-                else
-                    git add $CHANGES
-                    # XXX don't commit -a?
-                    git commit -a -F $message || exit
-                    echo "Note that we are using GIT now, so there needs to be a 'git push' to push your"
-                    echo "changes to the central repository"
-                fi
+                git add $CHANGES
+                # XXX don't commit -a?
+                git commit -a -F $message || exit
+		echo "after testing your changes, run"
+		echo "    git push origin $(get_branch_name)"
 		break ;;
 	    [nN] | no)
 		break ;;
