- scripts/tests/lib.py: - scripts/tests/test_log2.py: - scripts/log2:
Add splice_series() tests. Coverage is measured using kcov:
https://github.com/SimonKagstrom/kcov

diff --git a/scripts/log2 b/scripts/log2
--- a/scripts/log2
+++ b/scripts/log2
@@ -22,17 +22,7 @@
 
 # git commit wrapper, generates unified commit messages from patch headers
 
-. ${0%/*}/wd-functions.sh
-
-if ! $using_git; then
-    echo "ERROR: not in a git working directory."
-    exit 1
-fi
-
-scripts/check-cvs-add || exit 1
-
-trap 'rm -rf "$tmpdir"' EXIT
-tmpdir=$(mktemp -d /tmp/${0##*/}.XXXXXX)
+_libdir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
 
 log_entry() {
     local entry=$1
@@ -353,6 +343,21 @@ EOF
         return 1
     fi
 }
+
+# do not run "main" code if script is being sourced rather than executed
+[[ $0 != "$BASH_SOURCE" ]] && return
+
+. "$_libdir"/wd-functions.sh
+
+if ! $using_git; then
+    echo "ERROR: not in a git working directory."
+    exit 1
+fi
+
+"$_libdir"/check-cvs-add || exit 1
+
+trap 'rm -rf "$tmpdir"' EXIT
+tmpdir=$(mktemp -d /tmp/${0##*/}.XXXXXX)
 
 if test -e "$(git rev-parse --git-dir)/MERGE_HEAD"; then
     # Do not try to fabricate a commit message for merge commits, git itself
