scripts/osc_wrapper: Check if osc is available

diff --git a/scripts/osc_wrapper b/scripts/osc_wrapper
--- a/scripts/osc_wrapper
+++ b/scripts/osc_wrapper
@@ -2,9 +2,6 @@
 #
 # Building kernels with osc made easy
 
-command=
-spec=
-
 die()
 {
 	echo "$@" >&2
@@ -326,6 +323,12 @@ do_upload()
 	echo "  $WEBCLIENT/project/monitor?project=${home_project//:/%3A}"
 }
 
+command=
+spec=
+if ! osc help >/dev/null; then
+	echo "Cannot run osc" >&2
+	exit 1
+fi
 
 case "$1" in
 build | upload)
