scripts/osc_wrapper: Build against the KOTD projects
This fixes issues with missing packages like pesign-obs-integration.

diff --git a/scripts/osc_wrapper b/scripts/osc_wrapper
--- a/scripts/osc_wrapper
+++ b/scripts/osc_wrapper
@@ -69,34 +69,104 @@ find_spec()
 	return 1
 }
 
+get_branch()
+{
+	local res version sp
+
+	# First, try the local branch name
+	res=$(sed -ne 's|^ref: refs/heads/||p' .git/HEAD 2>/dev/null)
+	if test -n "$res"; then
+		if project_exists "$kotd_namespace:$res"; then
+			echo "$res"
+			return
+		fi
+		echo "Warning: $kotd_namespace:$res not found at $WEBCLIENT, trying harder" >&2
+		res=
+	else
+		echo "Warning: Could not determine your git branch" >&2
+	fi
+	# For SLE branches, try IBS_PROJECT
+	case "$IBS_PROJECT" in
+	SUSE:SLE-*)
+		# SUSE:SLE-10-SP4:Update -> 10-SP4:Update
+		version=${IBS_PROJECT#SUSE:SLE-}
+		# 10-SP4:Update -> 4:Update
+		sp=${version#*-SP}
+		if test "$sp" != "$version"; then
+			# 4:Update -> 4
+			sp=${sp%%:*}
+		else
+			sp=
+		fi
+		# 10-SP4:Update -> 10
+		version=${version%%-*}
+		if test "$version" -ge 11; then
+			res="SLE$version"
+		else
+			res="SLES$version"
+		fi
+		if test -n "$sp"; then
+			res="$res-SP$sp"
+		fi
+		if project_exists "$kotd_namespace:$res"; then
+			echo "$res"
+			return
+		fi
+		echo "Branch $kotd_namespace:$res not found at $WEBCLIENT" >&2
+		exit 1
+	esac
+	case "$OBS_PROJECT" in
+	openSUSE:Factory*)
+		if $internal; then
+			res=master
+		else
+			res=HEAD
+		fi
+		;;
+	openSUSE:*)
+		version=${OBS_PROJECT#openSUSE:}
+		version=${version%%:*}
+		res="openSUSE-$version"
+		;;
+	esac
+	if test -n "$res"; then
+		if project_exists "$kotd_namespace:$res"; then
+			echo "$res"
+			return
+		fi
+		echo "Branch $kotd_namespace:$res not found at $WEBCLIENT" >&2
+	else
+		echo "Could not determine the official name of this branch" >&2
+	fi
+	exit 1
+}
+
+
 setup_api()
 {
-	local prjvar=$1
+	local wanted=$1 internal=false kotd_namespace branch
 
-	PROJECT=${!prjvar}
-	if test -z "$PROJECT"; then
-		die "$prjvar not set in config.sh"
+	if test "$wanted" = "--ibs"; then
+		internal=true
+	elif test -z "$wanted"; then
+		if test -z "$OBS_PROJECT"; then
+			echo "Using the IBS"
+			internal=true
+		fi
 	fi
-}
-
-
-setup_ibs()
-{
-	API="-A https://api.suse.de"
-	WEBCLIENT="https://build.suse.de"
-	ARCHS="i586 x86_64 ia64 ppc ppc64 s390 s390x"
-	if test -z "$IBS_PROJECT"; then
-		IBS_PROJECT="openSUSE.org:$OBS_PROJECT"
+	if $internal; then
+		API="-A https://api.suse.de"
+		WEBCLIENT="https://build.suse.de"
+		ARCHS="i586 x86_64 ia64 ppc ppc64 s390 s390x"
+		kotd_namespace="Devel:Kernel"
+	else
+		API="-A https://api.opensuse.org"
+		WEBCLIENT="https://build.opensuse.org"
+		ARCHS="i586 x86_64"
+		kotd_namespace="Kernel"
 	fi
-	setup_api IBS_PROJECT
-}
-
-setup_obs()
-{
-	API="-A https://api.opensuse.org"
-	WEBCLIENT="https://build.opensuse.org"
-	ARCHS="i586 x86_64"
-	setup_api OBS_PROJECT
+	branch=$(get_branch) || exit
+	PROJECT="$kotd_namespace:$branch"
 }
 
 create_package()
@@ -139,7 +209,7 @@ project_exists()
 
 do_build()
 {
-	local osc_args=() debuginfo=false checks=false
+	local osc_args=() debuginfo=false checks=false api
 
 	while test $# -gt 0; do
 		case "$1" in
@@ -157,6 +227,10 @@ do_build()
 			;;
 		--no-checks | --nochecks)
 			checks=false
+			shift
+			;;
+		--ibs | --obs)
+			api=$1
 			shift
 			;;
 		-*)
@@ -183,13 +257,7 @@ do_build()
 	fi
 
 	arch=$(uname -m | sed 's/^i.86$/i586/')
-	if test -n "$OBS_PROJECT"; then
-		setup_obs
-	elif test -n "$IBS_PROJECT"; then
-		setup_ibs
-	else
-		die "Neither OBS_PROJECT nor IBS_PROJECT set in config.sh"
-	fi
+	setup_api $api
 
 	rm -rf "$(dirname "$spec")/.osc"
 	osc build --local-package --alternative-project="$PROJECT" \
@@ -200,25 +268,15 @@ do_build()
 
 do_upload()
 {
-	if test -n "$OBS_PROJECT"; then
-		internal=false
-	else
-		internal=true
-	fi
 	case $1 in
-	--ibs)
-		internal=true
+	--ibs | --obs)
+		setup_api $1
 		shift
 		;;
-	--obs)
-		shift
+	*)
+		setup_api
 		;;
 	esac
-	if $internal; then
-		setup_ibs
-	else
-		setup_obs
-	fi
 	case $# in
 	1)
 		home_project=$1
