scripts/PMU: Adjust for more maintainers' needs
  * Allow arbitrary kgraft project name
  * More specific variable name
  * Add package entries in one block
  * Eliminate nr_pkgs and guess number of entries from the past
  * Amended newlines in output messages
  * Fail better without IBS access
  * Improve non-existent prj message
  * Interactive git clean
  * Update readme

diff --git a/scripts/prepare-maint-update b/scripts/prepare-maint-update
--- a/scripts/prepare-maint-update
+++ b/scripts/prepare-maint-update
@@ -9,17 +9,19 @@ nrm=$(tput sgr0)
 
 sn="${0##*/}"
 if [ $# -lt 1 ]; then
-    printf "${Red}usage:${nrm} %s <product> [branch]\n" "$sn" >&2
+    printf "${Red}usage:${nrm} %s <product> [branch] [kgraft_prj]\n" "$sn" >&2
     exit 1
 fi
 tbranch="$1"
 prod="${1%-LTSS}"
 branch="${2:-$tbranch}"
+lp_proj="${3}"
 
 OSC_DIR="${OSC_DIR:-/tmp}"
 OSC="osc -A https://api.suse.de/"
 target="SUSE:SLE-${prod#SLE}:Update"
 prj="Devel:Kernel:${tbranch}:Submit"
+kgraft_dir="Devel:kGraft:patches"
 
 if [ ! -d "$KSOURCE_GIT" ]; then
     printf "${Red}Error: directory '%s' does not exist${nrm}\n" "$KSOURCE_GIT"
@@ -31,15 +33,24 @@ if [ ! -d "$OSC_DIR" ]; then
     echo "Please set OSC_DIR to a directory to use for OBS/IBS checkouts."
     exit 1
 fi
+if ! $OSC api /about >/dev/null ; then
+    echo "${Red}Error: Cannot login to OBS${nrm}"
+    printf "Check your SSH key setup in .oscrc for '%s'\n" "$OSC"
+    exit 1
+fi
 
 cd "$KSOURCE_GIT"
 git checkout "$branch"
 git pull --ff-only >/dev/null
 version=$(rpm/compute-PATCHVERSION.sh --patches .)
-upd=$($OSC ls "$target" \
-    | sed -rne "/^kernel-livepatch-${prod}_Update_[[:digit:]]+\$/ { s/^.*_// ; p }" \
-    | sort -n | tail -1)
-: $[upd++]
+if [ -n "$lp_proj" ] ; then
+    upd="${lp_proj##*_}"
+else
+    upd=$($OSC se -s --project "${kgraft_dir}:${prod}" \
+        | sed -rne "/^${kgraft_dir}:${prod}_Update_[[:digit:]]+\$/ { s/^.*_// ; p }" \
+        | sort -n | tail -1)
+    lp_proj="${prod}_Update_${upd}"
+fi
 
 printf "Product:           ${blu}%s${nrm}\n" "$prod"
 printf "Target branch:     ${blu}%s${nrm}\n" "$tbranch"
@@ -54,13 +65,13 @@ if ! git merge-base --is-ancestor "$branch" "$tbranch"; then
     printf "${Red}Warning: %s not merged into %s${nrm}\n\n" "$branch" "$tbranch" >&2
 fi
 
-printf "${grn}* Delete old %s IBS project...${nrm}" "$prj"
-$OSC rdelete -f -r -m "drop old maintenance update" "$prj" || true
+printf "${grn}* Delete old %s IBS project...${nrm}\n" "$prj"
+$OSC rdelete -f -r -m "drop old maintenance update" "$prj" || printf "Note: %s likely does not exist\n"
 rm -rf "${OSC_DIR}/${prj}"
 
-echo "${grn}* Pack kernel-source...${nrm}"
+echo "${grn}* Clean WC and pack kernel-source...${nrm}"
 cd $KSOURCE_GIT
-git clean -dfxq
+git clean -dxi
 scripts/tar-up.sh
 printf "${grn}* Create %s and upload kernel-source to IBS...${nrm}\n" "$prj"
 scripts/osc_wrapper upload --ibs --debug "$prj"
@@ -72,20 +83,30 @@ archs=''
 while read a; do
     archs="${archs}${archs:+ }${a#${smlp}}"
 done < <($OSC ls "$chanprj" | egrep "^$smlp")
-old_upd="${prod}_Update_$[upd-1]"
-inc_upd="s/${old_upd}/${prod}_Update_${upd}/g"
-fixme="s/(${version//./_})-[[:digit:]_]+-/\1-FIXME-/"
 
+kgraft_prj="${kgraft_dir}:${lp_proj}"
 printf "${grn}* Copy kernel-livepatch-%s_Update_%u package...${nrm}\n" \
     "$prod" "$upd"
-$OSC copypac "Devel:kGraft:patches:${prod}_Update_${upd}" \
+$OSC copypac "$kgraft_prj" \
     "kernel-livepatch-${prod}_Update_${upd}" "$prj"
+
+inc_upd="s/${prod}_Update_[[:digit:]]+/${prod}_Update_${upd}/g"
+fixme="s/(${version//./_})-[[:digit:]_]+-/\1-FIXME-/"
 printf "${grn}* Branch %s* and update _channel...${nrm}\n" "$smlp"
 for a in $archs; do
     printf "${grn}  * architecture %s...${nrm}\n" "$a"
     $OSC bco "$chanprj" "${smlp}${a}" "$prj"
     pushd "${prj}/${smlp}${a}" >/dev/null
-    sed -re "/${old_upd}/ { p ; ${inc_upd} ; ${fixme} }" -i _channel
+    # Copy last bunch packages of given product, update their versions and
+    # paste them in one block after last package
+    last_pkg=$(grep  -E "${prod}_Update_[[:digit:]]+" _channel | tail -1)
+    last_upd=$(echo "$last_pkg" | grep -oE "${prod}_Update_[[:digit:]]+" | tail -1)
+    prev_pkgs=$(grep -E "${last_upd}" _channel)
+    new_pkgs=$(echo -n "$prev_pkgs" | sed -re "${inc_upd} ; ${fixme} ; s/\$/\\\/")
+    # Assume no '|' in XML rows, escaping magic not to insert a trailing newline
+    sed -re "\|${last_pkg}| a \\
+${new_pkgs%\\}
+" -i _channel
     $OSC commit -m "update channel file"
     popd >/dev/null
 done
