- Pulled packaging changes from master.

diff --git a/scripts/series2git b/scripts/series2git
--- a/scripts/series2git
+++ b/scripts/series2git
@@ -1,4 +1,23 @@
 #!/bin/bash
+#############################################################################
+# Copyright (c) 2009 Novell, Inc.
+# All Rights Reserved.
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of version 2 of the GNU General Public License as
+# published by the Free Software Foundation.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.   See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, contact Novell, Inc.
+#
+# To contact Novell about this file by physical or electronic mail,
+# you may find current contact information at www.novell.com
+#############################################################################
 #
 # Apply the patch series to a linux git repository. Note that the generated
 # branch will differ each time, it is only meant as an alternative to quilt
@@ -6,7 +25,7 @@
 
 usage()
 {
-	echo "Usage: $0 -g <mainline kernel git> [-b <branch>] [-v] [-f]"
+	echo "Usage: $0 -g <mainline kernel git> [-b <branch>] [-v] [-f] [-s|-n] [-a]"
 	echo "branch is $branch by default"
 }
 
@@ -31,7 +50,16 @@ fi
 git=
 verbose=false
 force=false
-options=$(getopt -n "$0" -o b:g:vfh --long branch:,git:,verbose,force,help -- "$@")
+skip=true
+use_applied=false
+last_patch=
+. "$dir"/config.sh
+# sles10 doesn't use pristine stable patches
+case "$DIST_SET" in
+sles10* | sle10* )
+	skip=false
+esac
+options=$(getopt -n "$0" -o ab:g:vsnfh --long branch:,git:,verbose,use-applied,force,skip,no-skip,help -- "$@")
 if test $? != 0; then
 	usage >&2
 	exit 1
@@ -55,6 +83,18 @@ while test $# -gt 0; do
 		force=true
 		shift
 		;;
+	-a | --use-applied)
+		use_applied=true
+		shift
+		;;
+	-s | --skip)
+		skip=true
+		shift
+		;;
+	-n | --no-skip)
+		skip=false
+		shift
+		;;
 	-h | --help)
 		usage
 		exit 0
@@ -75,21 +115,39 @@ if test -z "$git"; then
 	exit 1
 fi
 
-if test -x "$dir"/../rpm/compute-PATCHVERSION.sh; then
-	base=$("$_")
+if ! $skip; then
+	base="$SRCVERSION"
 else
-	base=$("$dir"/compute-PATCHVERSION.sh)
+	if test -x "$dir"/../rpm/compute-PATCHVERSION.sh; then
+		base=$("$_")
+	else
+		base=$("$dir"/compute-PATCHVERSION.sh)
+	fi
 fi
-args=(--git "$git")
-$verbose && args[${#args[@]}]="--verbose"
-$force   && args[${#args[@]}]="--force"
-base_id=$("${0%/*}"/mainline-commit "${args[@]}" "$base") || exit
-echo "base is $base (${base_id:0:7})"
+if $use_applied ; then
+	cur_branch=$(l_git branch | sed -n 's/^\* //p')
+	if test "$cur_branch" != "$branch"; then
+		echo "branch is $cur_branch, cannot use current branch"
+		use_applied=false
+	fi
+fi
+if $use_applied ; then
+	last_patch=$(l_git show | sed -n 's/^ *Patch-name: //p')
+	if $force ; then
+		l_git reset --hard
+	fi
+else
+	args=(--git "$git")
+	$verbose && args[${#args[@]}]="--verbose"
+	$force   && args[${#args[@]}]="--force"
+	base_id=$("${0%/*}"/mainline-commit "${args[@]}" "$base") || exit
+	echo "base is $base (${base_id:0:7})"
 
-# workaround "cannot delete branch which you are currently on" errors
-l_git checkout -q HEAD^0 || exit
-l_git branch -f "$branch" "$base_id" || exit
-l_git checkout "$branch" || exit
+	# workaround "cannot delete branch which you are currently on" errors
+	l_git checkout -q HEAD^0 || exit
+	l_git branch -f "$branch" "$base_id" || exit
+	l_git checkout "$branch" || exit
+fi
 
 ex_hdr()
 {
@@ -137,10 +195,21 @@ apply_patch()
 	patches.kernel.org/patch-2.6.*.*-rc*)
 		;;
 	patches.kernel.org/patch-2.6.*)
-		echo "skipping $patch"
-		continue
+		if $skip; then
+			echo "skipping $patch"
+			continue
+		fi
 		;;
 	esac
+	if test -n "$last_patch"; then
+	    if test "$patch" != "$last_patch" ; then
+		echo "skipping $patch"
+		continue
+	    fi
+	    echo "skipping $patch"
+	    last_patch=
+	    continue
+	fi
 	if $verbose; then
 		echo "[ $patch ]"
 	fi
