scripts/sha2series: fixes to address review from jslaby

diff --git a/scripts/sha2series b/scripts/sha2series
--- a/scripts/sha2series
+++ b/scripts/sha2series
@@ -21,27 +21,30 @@ trap 'rm -rf "$tmpdir"' EXIT
 mbox_file=$tmpdir/mbox
 
 sha=$1
-author="$(git -C $LINUX_GIT/.git show -s --pretty='format:%ae' $sha)"
+author="$(git -C $LINUX_GIT show -s --pretty='format:%ae' $sha)"
 (
 	cd $LINUX_GIT
 	echo "$(git show -s --pretty='format:%h ("%s")' $sha) by $author"
 	b4 dig -c $sha -m $mbox_file 2>&1 | grep "https://"
 )
-grep "^Subject: \[PATCH" $mbox_file | grep -v "[[:space:]]\+0\+" | sed -e 's@\.*$@@' -e 's@.*[0-9]\+\][[:space:]]\+\(.*\)@"^\1"@' > $tmpdir/subjects
+
+if [ ! -s $mbox_file ]
+then
+	echo "Failed to dig the ML message" >&2
+	exit 1
+fi
+
+grep "^Subject: \[PATCH" $mbox_file | grep -v "[[:space:]]\+0\+/" | sed -e 's@\.*$@@' -e 's@.*[0-9]\+\][[:space:]]\+\(.*\)@"^\1"@' > $tmpdir/subjects
 
 nr_patches=$(wc -l $tmpdir/subjects | cut -d" " -f1)
-if [ $nr_patches -le 1 ]
-then
-	echo "Too few patches $nr_patches"
-	exit 0
-fi
+[ $nr_patches -le 1 ] && exit 0
 
 echo "Found $nr_patches patches on the ML"
 
 patchfiles=$(lsdiff --strip 1 $mbox_file | sort -u)
-base_range="$(git -C $LINUX_GIT/.git describe $sha | cut -d- -f1)..origin/master"
+base_range="$(git -C $LINUX_GIT describe --abbrev=0 --match="v*" $sha)..origin/master"
 
 shift
 cmd="$@"
 : ${cmd:="echo"}
-xargs -d '\n' -I {} echo --grep={} < $tmpdir/subjects | xargs git -C $LINUX_GIT/.git --no-pager log -i --pretty="format:%H" --author=$author $base_range | xargs $cmd
+xargs -d '\n' -I {} echo --grep={} < $tmpdir/subjects | xargs git -C $LINUX_GIT --no-pager log -i --pretty="format:%H" --author=$author $base_range | xargs $cmd
