tar-up: Refuse to tar up upstream release without upstream source
Not using upstream sources for ustream Linux release is source of
endless errors. Refuse to tar up sources when upstream sources are
needed and not provided. Advise to use mirror-kernel-sources script. Add
a --git option to override this check for the case when recent upstream
release is tagged but not uploaded to kernel.org.

diff --git a/scripts/tar-up b/scripts/tar-up
--- a/scripts/tar-up
+++ b/scripts/tar-up
@@ -29,6 +29,7 @@ ignore_kabi=
 mkspec_args=()
 arch=
 flavor=
+targall_from_git=
 source rpm/config.sh
 until [ "$#" = "0" ] ; do
   case "$1" in
@@ -39,6 +40,10 @@ until [ "$#" = "0" ] ; do
     -d|--dir)
       build_dir=$2
       shift 2
+      ;;
+    --git)
+      targall_from_git=1
+      shift
       ;;
     --embargo)
       # obsolete
@@ -78,6 +83,7 @@ ${0##*/} perpares a 'kernel-source' package for submission into autobuild
 these options are recognized:
     -nf                to proceed if a new unknown .config option is found during make oldconfig
     -i                 ignore kabi failures
+    --git              skip searching for upstream tarball
     -d, --dir=DIR      create package in DIR instead of default kernel-source$VARIANT
     -a, --arch=ARCH    create package for architecture ARCH only
     -f, --flavor=FLAVOR create package for FLAVOR only
@@ -120,7 +126,9 @@ get_tarball()
 {
     local version=$1 suffix=$2 dest=$3 url=$4 tarball compress sig
 
-    tarball=$(_find_tarball "$version" "$suffix")
+    if [ -z "$targall_from_git" ] ; then
+        tarball=$(_find_tarball "$version" "$suffix")
+    fi
     if test -n "$tarball"; then
         sig="$(get_kernel_sig "$dest/linux-$version.$suffix")"
         cp -p "$tarball" "$dest/linux-$version.$suffix.part" || exit
@@ -141,7 +149,17 @@ get_tarball()
         fi
         return
     fi
-    echo "Warning: could not find linux-$version.$suffix, trying to create it from git" >&2
+    if [ -z "$targall_from_git" ] ; then
+        case "$version" in
+            *-*) # A rc release or git snapshot
+                ;;
+            *)
+                echo "Could not find linux-$version.$suffix" >&2
+                echo "Please use mirror-linux-tarballs script to fetch upstream sources" >&2
+                exit 1
+        esac
+    fi
+    echo "Trying to create linux-$version.$suffix from git" >&2
     case "$suffix" in
     tar.bz2)
         compress="bzip2 -9"
